// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

export function ArchiveGroup(id: string, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(4155802806, id, archived);
}

export function ArchiveInstitution(id: string, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(3475186395, id, archived);
}

export function ArchiveMember(id: string, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(2862030925, id, archived);
}

export function CreateGroup(name: string, iconKey: string): $CancellablePromise<wire$0.GroupDTO> {
    return $Call.ByID(953874670, name, iconKey);
}

export function CreateInstitution(name: string, institutionType: string, iconKey: string): $CancellablePromise<wire$0.InstitutionDTO> {
    return $Call.ByID(2695348579, name, institutionType, iconKey);
}

export function CreateMember(name: string, iconKey: string): $CancellablePromise<wire$0.MemberDTO> {
    return $Call.ByID(1090572709, name, iconKey);
}

export function ListGroups(includeArchived: boolean): $CancellablePromise<wire$0.GroupDTO[] | null> {
    return $Call.ByID(1226754055, includeArchived);
}

export function ListInstitutions(includeArchived: boolean): $CancellablePromise<wire$0.InstitutionDTO[] | null> {
    return $Call.ByID(4173405712, includeArchived);
}

export function ListMembers(includeArchived: boolean): $CancellablePromise<wire$0.MemberDTO[] | null> {
    return $Call.ByID(4105724226, includeArchived);
}

export function SetGroupIcon(id: string, iconKey: string): $CancellablePromise<void> {
    return $Call.ByID(2433362781, id, iconKey);
}

export function SetInstitutionIcon(id: string, iconKey: string): $CancellablePromise<void> {
    return $Call.ByID(3848902576, id, iconKey);
}

export function SetMemberIcon(id: string, iconKey: string): $CancellablePromise<void> {
    return $Call.ByID(2720808482, id, iconKey);
}

export function UpdateGroup(id: string, name: string): $CancellablePromise<wire$0.GroupDTO> {
    return $Call.ByID(513733857, id, name);
}

export function UpdateInstitution(id: string, name: string): $CancellablePromise<wire$0.InstitutionDTO> {
    return $Call.ByID(3421171796, id, name);
}

export function UpdateMember(id: string, name: string): $CancellablePromise<wire$0.MemberDTO> {
    return $Call.ByID(582797560, id, name);
}
