// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QuoteSeriesDTO is the bounded local quote-history read model used by
 * Market Data charts. Observations keep every matching fact; Points are the
 * deterministically selected chart series.
 */
export interface QuoteSeriesDTO {
    "range": string;
    "displayCurrency"?: string;
    "baseCurrency"?: string;
    "quoteCurrency"?: string;
    "points": QuoteSeriesPointDTO[] | null;
    "observations": QuoteSeriesPointDTO[] | null;
    "outsideRange": boolean;
}

/**
 * QuoteSeriesPointDTO is one local observation in the requested display
 * direction. Value is a canonical decimal string.
 */
export interface QuoteSeriesPointDTO {
    "quotedAt": string;
    "value": string;
    "sourceKind": string;
    "sourceKey": string;
    "delayed": boolean;
}
