// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppendManualFXQuote(baseCurrency: string, quoteCurrency: string, rate: string, quotedAt: string): $CancellablePromise<wire$0.FXQuoteDTO> {
    return $Call.ByID(3624550014, baseCurrency, quoteCurrency, rate, quotedAt);
}

export function AppendManualInstrumentQuote(instrumentID: string, unitPrice: string, quotedAt: string, delayed: boolean): $CancellablePromise<wire$0.InstrumentQuoteDTO> {
    return $Call.ByID(2443553223, instrumentID, unitPrice, quotedAt, delayed);
}

export function CurrentFXQuote(currencyA: string, currencyB: string): $CancellablePromise<wire$0.FXQuoteDTO | null> {
    return $Call.ByID(431736251, currencyA, currencyB);
}

export function CurrentInstrumentQuote(instrumentID: string): $CancellablePromise<wire$0.InstrumentQuoteDTO | null> {
    return $Call.ByID(762255110, instrumentID);
}

export function FXQuoteSeries(currencyA: string, currencyB: string, trendRange: string, sourceFilter: string): $CancellablePromise<$models.QuoteSeriesDTO> {
    return $Call.ByID(290670193, currencyA, currencyB, trendRange, sourceFilter);
}

export function InstrumentQuoteSeries(instrumentID: string, trendRange: string, sourceFilter: string): $CancellablePromise<$models.QuoteSeriesDTO> {
    return $Call.ByID(2174474708, instrumentID, trendRange, sourceFilter);
}

export function ListFXPreferences(): $CancellablePromise<wire$0.FXPreferenceDTO[] | null> {
    return $Call.ByID(4067275526);
}

export function SetFXPreference(currencyA: string, currencyB: string, source: string): $CancellablePromise<wire$0.FXPreferenceDTO> {
    return $Call.ByID(4015579573, currencyA, currencyB, source);
}
