// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GainScopeRequest mirrors domain.GainScope: an empty request is the explicit
 * portfolio scope; setting AccountID or InstrumentID narrows the calculation.
 */
export interface GainScopeRequest {
    "accountId"?: string | null;
    "instrumentId"?: string | null;
}
