// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

/**
 * GainScopeRequest mirrors domain.GainScope: an empty request is the explicit
 * portfolio scope; setting AccountID or InstrumentID narrows the calculation.
 */
export interface GainScopeRequest {
    "accountId"?: string | null;
    "instrumentId"?: string | null;
}

export interface HoldingAmountsDTO {
    "quantity": string;
    "totalCost"?: wire$0.MoneyView | null;
    "currentValue"?: wire$0.MoneyView | null;
    "unrealizedGain"?: wire$0.SignedMoneyView | null;
    "costMissingReason"?: string;
    "valueMissingReason"?: string;
    "gainMissingReason"?: string;
}

export interface InstrumentHoldingMemberDTO {
    "holdingId": string;
    "accountId": string;
    "accountName": string;
    "amounts": HoldingAmountsDTO;
}

export interface InstrumentHoldingsDTO {
    "instrumentId": string;
    "name": string;
    "symbol": string;
    "quoteCurrency": string;
    "quantityUnit": string;
    "archived": boolean;
    "amounts": HoldingAmountsDTO;
    "holdings": InstrumentHoldingMemberDTO[] | null;
}
