// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface RestoreConfirmRequest {
    "token": string;
    "confirmation": string;
    "acknowledged": boolean;
    "restoreChrome": boolean;
    "restoreFormat": boolean;
    "restoreRouting": boolean;
}

export interface RestorePreviewDTO {
    "cancelled": boolean;
    "token"?: string;
    "fileName"?: string;
    "createdAt"?: string;
    "appVersion"?: string;
    "appBuild"?: string;
    "schemaVersion"?: number;
    "formatVersion"?: number;
    "backupHousehold"?: string;
    "backupCurrency"?: string;
    "backupAccounts": number;
    "backupHoldings": number;
    "backupActivities": number;
    "currentHousehold"?: string;
    "currentCurrency"?: string;
    "currentAccounts": number;
    "currentHoldings": number;
    "currentActivities": number;
    "settingsReadable": boolean;
    "hasOpenSession": boolean;
}

export interface RestoreResultDTO {
    "restartRequired": boolean;
}
