// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConfirmRestore(request: $models.RestoreConfirmRequest): $CancellablePromise<$models.RestoreResultDTO> {
    return $Call.ByID(3049288691, request);
}

export function InspectBackup(): $CancellablePromise<$models.RestorePreviewDTO> {
    return $Call.ByID(4198348609);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(1664768183);
}
