// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface OpenProductCommand {
    "accountId": string;
    "currency": string;
    "principal": string;
    "openingFee": string | null;
    "effectiveAt": string;
    "terms": ProductTermsInput;
    "policy": ProductPolicyInput;
}

export interface ProductPolicyInput {
    "accessKind": string;
    "unlockOn": string | null;
    "settlementDays": number | null;
    "dayBasis": string | null;
    "receiptOnOverride": string | null;
    "normalExitFee": string | null;
    "earlyKind": string;
    "earlySettlementDays": number | null;
    "earlyDayBasis": string | null;
    "earlyFee": string | null;
    "earlyAmountMode": string | null;
    "earlyGrossAmount": string | null;
    "note": string | null;
}

export interface ProductTermsInput {
    "kind": string;
    "name": string;
    "note": string | null;
    "startOn": string;
    "maturityOn": string | null;
    "interestMode": string;
    "annualRate": string | null;
    "annualRatePercent": string | null;
    "maturityInterest": string | null;
    "interestPaidThroughOn": string | null;
}

export interface ReceiveInterestCommand {
    "productId": string;
    "amount": string;
    "effectiveAt": string;
    "interestPaidThroughOn": string | null;
    "remainingInterest": string | null;
}

export interface RecordExistingProductCommand {
    "accountId": string;
    "currency": string;
    "principal": string;
    "totalCostBasis": string;
    "currentValue": string;
    "cashExcludesProduct": boolean;
    "effectiveAt": string;
    "terms": ProductTermsInput;
    "policy": ProductPolicyInput;
}

export interface RenewProductCommand {
    "settle": SettleProductCommand;
    "principal": string;
    "openingFee": string | null;
    "terms": ProductTermsInput;
    "policy": ProductPolicyInput;
}

export interface SettleProductCommand {
    "productId": string;
    "returnedPrincipal": string | null;
    "interest": string | null;
    "grossProceeds": string | null;
    "fee": string | null;
    "effectiveAt": string;
    "releaseReservationIds": string[] | null;
}

export interface UndoProductCommand {
    "operationId": string;
}
