// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CSVPreviewStats {
    "createAccounts": number;
    "createHoldings": number;
    "createInstruments": number;
    "createMembers": number;
    "createInstitutions": number;
    "createGroups": number;
    "references": number;
    "warnings": number;
    "errors": number;
    "duplicates": number;
}

export interface CSVRowError {
    "row": number;
    "field": string;
    "source"?: string;
    "code": string;
    "message": string;
    "suggestion"?: string;
}

export interface CSVUnresolvedAction {
    "kind": string;
    "name": string;
    "action": string;
    "mapTo"?: string;
}

export interface CSVUnresolvedName {
    "kind": string;
    "name": string;
    "field": string;
    "row": number;
}

export interface CSVWarning {
    "row": number;
    "code": string;
    "message": string;
}

export enum SecretStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SecretStatusMissing = "missing",
    SecretStatusAvailable = "available",
    SecretStatusUnavailable = "unavailable",
    SecretStatusLocked = "locked",
    SecretStatusSessionOnly = "session_only",
};
