// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DerivedDataRebuildResult {
    "from": string;
    "to": string;
    "snapshotDays": number;
    "incompleteDays": number;
}

export interface HistoricalOverviewAllocation {
    "key": string;
    "amount": string;
    "share": string;
}

export interface HistoricalOverviewCell {
    "status": string;
    "included": boolean;
    "complete": boolean;
    "currency": string;
    "nativeAmount": string | null;
    "baseAmount": string | null;
    "quantity": string | null;
    "assetClass": string;
    "manual": boolean;
    "valueSourceAt": string;
    "valueSourceId": string;
    "price": HistoricalOverviewEvidence | null;
    "fx": HistoricalOverviewEvidence | null;
    "missing": string[] | null;
}

export interface HistoricalOverviewEvidence {
    "id": string;
    "source": string;
    "effectiveAt": string;
    "marketDate": string;
    "freshness": string;
}

/**
 * HistoricalOverviewResult is a presentation read model, not a saved snapshot.
 * Amounts are exact decimal strings. Nil means unknown, never zero.
 */
export interface HistoricalOverviewResult {
    "timezone": string;
    "originDate": string;
    "lastClosedDate": string;
    "capturedAt": string;
    "inputGeneration": number;
    "resolverPolicy": string;
    "left": HistoricalOverviewState;
    "right": HistoricalOverviewState | null;
    "change": HistoricalOverviewTotalsChange | null;
    "rows": HistoricalOverviewRow[] | null;
}

export interface HistoricalOverviewRow {
    "key": string;
    "parentKey": string;
    "kind": string;
    "name": string;
    "role": string;
    "left": HistoricalOverviewCell | null;
    "right": HistoricalOverviewCell | null;
    "baseChange": string | null;
    "nativeChange": string | null;
    "quantityChange": string | null;
    "changed": boolean;
}

export interface HistoricalOverviewState {
    "date": string;
    "cutoffAt": string;
    "current": boolean;
    "currency": string;
    "complete": boolean;
    "assets": string | null;
    "liabilities": string | null;
    "netWorth": string | null;
    "knownAssets": string;
    "knownLiabilities": string;
    "byClass": HistoricalOverviewAllocation[] | null;
    "byCurrency": HistoricalOverviewAllocation[] | null;
}

/**
 * HistoricalOverviewTotalsChange is right minus left, not return attribution.
 * Each amount remains nil when either corresponding total is incomplete.
 */
export interface HistoricalOverviewTotalsChange {
    "assets": string | null;
    "liabilities": string | null;
    "netWorth": string | null;
}

export interface OpenProductCommand {
    "effectiveLocalDate"?: string;
    "effectiveLocalTime"?: string;
    "accountId": string;
    "currency": string;
    "principal": string;
    "openingFee": string | null;
    "effectiveAt": string;
    "terms": ProductTermsInput;
    "policy": ProductPolicyInput;
}

export interface ProductPolicyInput {
    "accessibleAmountCap": string | null;
    "accessKind": string;
    "unlockOn": string | null;
    "settlementDays": number | null;
    "dayBasis": string | null;
    "receiptOnOverride": string | null;
    "normalExitFee": string | null;
    "earlyKind": string;
    "earlySettlementDays": number | null;
    "earlyDayBasis": string | null;
    "earlyFee": string | null;
    "earlyAmountMode": string | null;
    "earlyGrossAmount": string | null;
    "note": string | null;
}

export interface ProductTermsInput {
    "kind": string;
    "name": string;
    "note": string | null;
    "startOn": string;
    "maturityOn": string | null;
    "interestMode": string;
    "annualRate": string | null;
    "annualRatePercent": string | null;
    "maturityInterest": string | null;
    "interestPaidThroughOn": string | null;
}

export interface ReceiveInterestCommand {
    "effectiveLocalDate"?: string;
    "effectiveLocalTime"?: string;
    "productId": string;
    "amount": string;
    "effectiveAt": string;
    "interestPaidThroughOn": string | null;
    "remainingInterest": string | null;
}

export interface RecordExistingProductCommand {
    "accountId": string;
    "currency": string;
    "principal": string;
    "totalCostBasis": string;
    "currentValue": string;
    "cashExcludesProduct": boolean;
    "effectiveAt": string;
    "terms": ProductTermsInput;
    "policy": ProductPolicyInput;
}

export interface RenewProductCommand {
    "settle": SettleProductCommand;
    "principal": string;
    "openingFee": string | null;
    "terms": ProductTermsInput;
    "policy": ProductPolicyInput;
}

export interface SettleProductCommand {
    "effectiveLocalDate"?: string;
    "effectiveLocalTime"?: string;
    "productId": string;
    "returnedPrincipal": string | null;
    "interest": string | null;
    "grossProceeds": string | null;
    "fee": string | null;
    "effectiveAt": string;
    "releaseReservationIds": string[] | null;
}

export interface UndoProductCommand {
    "operationId": string;
}
