// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

/**
 * AccountFilterRequest mirrors domain.AccountFilter.
 */
export interface AccountFilterRequest {
    "includeArchived"?: boolean;
    "memberId"?: string | null;
    "institutionId"?: string | null;
    "groupId"?: string | null;
    "accountType"?: string | null;
    "ownershipScope"?: string;
}

/**
 * CreateAccountRequest mirrors application.AccountInput's create shape. All
 * fields except Name/AccountType/BalanceSheetRole/TrackingMode/
 * DefaultCurrency are optional.
 */
export interface CreateAccountRequest {
    "name": string;
    "accountType": string;
    "balanceSheetRole": string;
    "trackingMode": string;
    "defaultCurrency": string;
    "institutionId"?: string | null;
    "groupId"?: string | null;
    "note"?: string | null;
    "iconKey"?: string | null;
    "includeInNetWorth": boolean;
    "includeInPortfolio": boolean;
    "includeInLiquidAssets": boolean;
    "openedOn"?: string | null;
    "closedOn"?: string | null;
    "ownership"?: wire$0.OwnershipShareDTO[] | null;
    "ownerIds"?: string[] | null;
    "ownershipPercentages"?: string[] | null;
    "initialAmount"?: string;
}

/**
 * UpdateAccountRequest follows the "Set flags" pattern required by
 * application.AccountInput: a nil pointer means
 * "leave unchanged," a non-nil pointer to an empty string means "clear."
 * Boolean fields use *bool for the same reason.
 */
export interface UpdateAccountRequest {
    "name"?: string | null;
    "accountType"?: string | null;
    "balanceSheetRole"?: string | null;
    "trackingMode"?: string | null;
    "defaultCurrency"?: string | null;
    "institutionId"?: string | null;
    "institutionIdSet"?: boolean;
    "groupId"?: string | null;
    "groupIdSet"?: boolean;
    "note"?: string | null;
    "noteSet"?: boolean;
    "iconKey"?: string | null;
    "iconKeySet"?: boolean;
    "includeInNetWorth"?: boolean | null;
    "includeInPortfolio"?: boolean | null;
    "includeInLiquidAssets"?: boolean | null;
    "openedOn"?: string | null;
    "openedOnSet"?: boolean;
    "closedOn"?: string | null;
    "closedOnSet"?: boolean;
    "ownership"?: wire$0.OwnershipShareDTO[] | null;
    "ownerIds"?: string[] | null;
    "ownershipPercentages"?: string[] | null;
    "initialAmount"?: string | null;
}
