// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AccountValuation(id: string): $CancellablePromise<wire$0.AccountValuationDTO> {
    return $Call.ByID(491368181, id);
}

export function AccountValuations(request: $models.AccountFilterRequest): $CancellablePromise<wire$0.AccountValuationDTO[] | null> {
    return $Call.ByID(2700983538, request);
}

export function AppendAccountValue(id: string, amount: string, effectiveAt: string): $CancellablePromise<wire$0.AccountValueDTO> {
    return $Call.ByID(4000997639, id, amount, effectiveAt);
}

export function ArchiveAccount(id: string, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(1737544158, id, archived);
}

export function CreateAccount(request: $models.CreateAccountRequest): $CancellablePromise<wire$0.AccountRecordDTO> {
    return $Call.ByID(2065681190, request);
}

export function ListAccounts(request: $models.AccountFilterRequest): $CancellablePromise<wire$0.AccountRecordDTO[] | null> {
    return $Call.ByID(1600073255, request);
}

export function SetAccountIcon(id: string, iconKey: string): $CancellablePromise<void> {
    return $Call.ByID(3400625073, id, iconKey);
}

export function UpdateAccount(id: string, request: $models.UpdateAccountRequest): $CancellablePromise<wire$0.AccountRecordDTO> {
    return $Call.ByID(2493331453, id, request);
}
