// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum Accent {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AccentIndigo = "indigo",
    AccentLavender = "lavender",
    AccentMint = "mint",
    AccentSky = "sky",
    AccentPeach = "peach",
};

export enum Appearance {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AppearanceSystem = "system",
    AppearanceLight = "light",
    AppearanceDark = "dark",
};

export enum Language {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LanguageSystem = "system",
    LanguageEnglish = "en",
    LanguageZhCN = "zh-CN",
    LanguageZhTW = "zh-TW",
};
