// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfoDTO mirrors internal/version's package-level identity constants.
 */
export interface AppInfoDTO {
    "name": string;
    "appId": string;
    "description": string;
    "version": string;
    "build": string;
}

/**
 * StartupDTO is the blocked-startup contract.
 * Available is a successful DTO either way so the frontend can render the
 * blocked page without calling any other service — those stay unregistered
 * when the database could not be opened.
 */
export interface StartupDTO {
    "available": boolean;
    "code"?: string;
    "field"?: string;
    "message"?: string;
    "foundSchemaVersion"?: number | null;
    "supportedSchemaVersion"?: number | null;
}
