// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppInfo(): $CancellablePromise<$models.AppInfoDTO> {
    return $Call.ByID(2979313974);
}

export function Startup(): $CancellablePromise<$models.StartupDTO> {
    return $Call.ByID(1866289316);
}
