// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

/**
 * AnalysisQueryRequest is the wire form of domain.AnalysisQuery. IDs remain
 * strings at the IPC boundary; conversion validates and canonicalizes them
 * before the application service sees the query.
 */
export interface AnalysisQueryRequest {
    "scopeKind": string;
    "scopeId"?: string;
    "from": string;
    "to": string;
    "valuation": string;
    "basis": string;
    "includeCash": boolean;
    "accountId"?: string | null;
    "currency"?: string | null;
    "assetClass"?: string;
    "instrumentId"?: string | null;
    "memberId"?: string | null;
}

/**
 * Aliases keep the converter names local to this package while the actual
 * wire contract remains in the shared wire package.
 */
export type AssetChangeDTO = wire$0.AssetChangeDTO;

export type AssetDriverDetailDTO = wire$0.AssetDriverDetailDTO;

export type AssetTrendDTO = wire$0.AssetTrendDTO;

export type CategoriesDTO = wire$0.CategoriesDTO;

export type CategoryDetailDTO = wire$0.CategoryDetailDTO;
