// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AssetChange(request: $models.AnalysisQueryRequest): $CancellablePromise<$models.AssetChangeDTO> {
    return $Call.ByID(2567079814, request);
}

export function AssetDriverDetail(request: $models.AnalysisQueryRequest, driverKey: string): $CancellablePromise<$models.AssetDriverDetailDTO> {
    return $Call.ByID(592674653, request, driverKey);
}

export function AssetTrend(request: $models.AnalysisQueryRequest, granularity: string, metric: string): $CancellablePromise<$models.AssetTrendDTO> {
    return $Call.ByID(1351440837, request, granularity, metric);
}

export function Categories(request: $models.AnalysisQueryRequest, categoryType: string): $CancellablePromise<$models.CategoriesDTO> {
    return $Call.ByID(2659273958, request, categoryType);
}

export function CategoryDetail(request: $models.AnalysisQueryRequest, categoryType: string, rowKey: string): $CancellablePromise<$models.CategoryDetailDTO> {
    return $Call.ByID(1774987935, request, categoryType, rowKey);
}
