// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as marketdata$0 from "../../../../waltwang/nestworth-go/internal/wailsapi/marketdata/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "marketdata.refresh.completed": marketdata$0.RefreshCompletedPayload;
        }
    }
}
