// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RefreshCompletedPayload is the event payload for RefreshCompletedEvent.
 * RequestID lets the frontend ignore a completion for an abandoned request
 * (the "stale completion" rule: ignore a completion for an abandoned
 * request); Error is the same apierror.WireError JSON shape a
 * synchronous method would have returned, or empty on success. Exported so
 * main.go can register it with application.RegisterEvent for a typed
 * TypeScript event payload.
 */
export interface RefreshCompletedPayload {
    "requestId": string;
    "status": string;
    "result"?: RefreshResultDTO | null;
    "error"?: string;
}

/**
 * RefreshResultDTO mirrors application.RefreshResult.
 */
export interface RefreshResultDTO {
    "items": RefreshTargetResultDTO[] | null;
    "rateLimited": boolean;
}

/**
 * RefreshTargetResultDTO mirrors application.RefreshTargetResult.
 */
export interface RefreshTargetResultDTO {
    "targetKey": string;
    "kind": string;
    "status": string;
    "errorCode"?: string;
}

export interface SyncBlockerDTO {
    "targetKey": string;
    "code": string;
    "reason": string;
}

export interface SyncItemDTO {
    "targetKey": string;
    "kind": string;
    "status": string;
    "detail"?: string;
    "provider"?: string;
}

export interface SyncJobDTO {
    "jobId": string;
    "workspaceId": string;
    "householdId": string;
    "planRevision": string;
    "sequence": number;
    "phase": string;
    "outcome": string;
    "scope": SyncRequestDTO;
    "estimatedRequests": number;
    "completedRequests": number;
    "targetCount": number;
    "completedTargets": number;
    "snapshotDaysPlanned": number;
    "snapshotDaysRebuilt": number;
    "committedBatches": number;
    "items"?: SyncItemDTO[] | null;
    "blockers"?: SyncBlockerDTO[] | null;
    "prerequisites"?: SyncBlockerDTO[] | null;
    "nextEligibilityAt"?: string;
    "errorCode"?: string;
}

export interface SyncPlanPreviewDTO {
    "asOf": string;
    "configRevision": string;
    "scope": SyncRequestDTO;
    "estimatedRequestCount": number;
    "snapshotWorkEstimate": number;
    "unresolved"?: SyncBlockerDTO[] | null;
    "instrumentTargets": number;
    "fxTargets": number;
    "latestInstrumentCount": number;
    "latestFxCount": number;
    "fetchRanges": number;
}

export interface SyncRequestDTO {
    "scope": string;
    "instrumentId"?: string;
    "currencyA"?: string;
    "currencyB"?: string;
    "forceRecheck"?: boolean;
}

export interface SyncStartResultDTO {
    "job": SyncJobDTO;
    "attached": boolean;
    "conflict": boolean;
    "reason"?: string;
}
