// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface HealthIssueDTO {
    "id": string;
    "kind": string;
    "severity": string;
    "groupKey": string;
    "targetKey": string;
    "label"?: string;
    "provider"?: string;
    "instrumentId"?: string;
    "accountId"?: string;
    "currencyA"?: string;
    "currencyB"?: string;
    "rangeStart"?: string;
    "rangeEnd"?: string;
    "rangeCount"?: number;
    "code"?: string;
    "reason"?: string;
    "action": string;
    "executable": boolean;
    "collapsed"?: boolean;
}

/**
 * InstrumentSearchHitDTO is a Yahoo search candidate used to prefill the
 * Instrument form. Empty optional identity fields stay omitted so the UI can
 * keep whatever the user already typed.
 */
export interface InstrumentSearchHitDTO {
    "providerKey": string;
    "providerSymbol": string;
    "name": string;
    "symbol": string;
    "type": string;
    "marketCode"?: string;
    "countryCode"?: string;
    "quoteCurrency"?: string;
    "exchange"?: string;
}

export interface MarketDataHealthReportDTO {
    "healthy": boolean;
    "incompleteSince"?: string;
    "coverageThrough"?: string;
    "lastFinalizedMarketDate"?: string;
    "issueCount": number;
    "executableCount": number;
    "prerequisiteCount": number;
    "snapshotDays": number;
    "issues"?: HealthIssueDTO[] | null;
}

/**
 * RefreshCompletedPayload is the event payload for RefreshCompletedEvent.
 * RequestID lets the frontend ignore a completion for an abandoned request
 * (the "stale completion" rule: ignore a completion for an abandoned
 * request); Error is the same apierror.WireError JSON shape a
 * synchronous method would have returned, or empty on success. Exported so
 * main.go can register it with application.RegisterEvent for a typed
 * TypeScript event payload.
 */
export interface RefreshCompletedPayload {
    "requestId": string;
    "status": string;
    "result"?: RefreshResultDTO | null;
    "error"?: string;
}

export interface RefreshProgressPayload {
    "requestId": string;
    "item": SyncItemDTO;
}

/**
 * RefreshResultDTO mirrors application.RefreshResult.
 */
export interface RefreshResultDTO {
    "items": RefreshTargetResultDTO[] | null;
    "rateLimited": boolean;
}

/**
 * RefreshTargetResultDTO mirrors application.RefreshTargetResult.
 */
export interface RefreshTargetResultDTO {
    "targetKey": string;
    "kind": string;
    "status": string;
    "errorCode"?: string;
}

export interface SyncBlockerDTO {
    "targetKey": string;
    "code": string;
    "reason": string;
}

export interface SyncItemDTO {
    "label"?: string;
    "symbol"?: string;
    "startDate"?: string;
    "endDate"?: string;
    "targetKey": string;
    "kind": string;
    "status": string;
    "detail"?: string;
    "provider"?: string;
}

export interface SyncJobDTO {
    "current"?: SyncItemDTO | null;
    "jobId": string;
    "workspaceId": string;
    "householdId": string;
    "planRevision": string;
    "sequence": number;
    "phase": string;
    "outcome": string;
    "scope": SyncRequestDTO;
    "estimatedRequests": number;
    "completedRequests": number;
    "targetCount": number;
    "completedTargets": number;
    "snapshotDaysPlanned": number;
    "snapshotDaysRebuilt": number;
    "committedBatches": number;
    "items"?: SyncItemDTO[] | null;
    "blockers"?: SyncBlockerDTO[] | null;
    "prerequisites"?: SyncBlockerDTO[] | null;
    "nextEligibilityAt"?: string;
    "errorCode"?: string;
}

export interface SyncPlanPreviewDTO {
    "items"?: SyncItemDTO[] | null;
    "asOf": string;
    "configRevision": string;
    "scope": SyncRequestDTO;
    "estimatedRequestCount": number;
    "snapshotWorkEstimate": number;
    "unresolved"?: SyncBlockerDTO[] | null;
    "instrumentTargets": number;
    "fxTargets": number;
    "latestInstrumentCount": number;
    "latestFxCount": number;
    "fetchRanges": number;
}

export interface SyncRequestDTO {
    "scope": string;
    "instrumentId"?: string;
    "currencyA"?: string;
    "currencyB"?: string;
    "forceRecheck"?: boolean;
}

export interface SyncStartResultDTO {
    "job": SyncJobDTO;
    "attached": boolean;
    "conflict": boolean;
    "reason"?: string;
}
