// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RefreshCompletedPayload is the event payload for RefreshCompletedEvent.
 * RequestID lets the frontend ignore a completion for an abandoned request
 * (the "stale completion" rule: ignore a completion for an abandoned
 * request); Error is the same apierror.WireError JSON shape a
 * synchronous method would have returned, or empty on success. Exported so
 * main.go can register it with application.RegisterEvent for a typed
 * TypeScript event payload.
 */
export interface RefreshCompletedPayload {
    "requestId": string;
    "status": string;
    "result"?: RefreshResultDTO | null;
    "error"?: string;
}

/**
 * RefreshResultDTO mirrors application.RefreshResult.
 */
export interface RefreshResultDTO {
    "items": RefreshTargetResultDTO[] | null;
    "rateLimited": boolean;
}

/**
 * RefreshTargetResultDTO mirrors application.RefreshTargetResult.
 */
export interface RefreshTargetResultDTO {
    "targetKey": string;
    "kind": string;
    "status": string;
    "errorCode"?: string;
}
