// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelAllAndWait(): $CancellablePromise<void> {
    return $Call.ByID(714817123);
}

/**
 * CancelRefresh cancels the in-flight refresh started under requestID, if
 * any, and emits a cancelled completion event. Calling it for an unknown or
 * already-completed requestID is a no-op, not an error: the frontend does not
 * need to race its own completion event to decide whether cancellation is
 * still meaningful.
 */
export function CancelRefresh(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(2389924325, requestID);
}

export function CancelSyncJob(jobID: string): $CancellablePromise<$models.SyncJobDTO> {
    return $Call.ByID(1970761316, jobID);
}

export function CoinGeckoQuoteCurrencies(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2012258955);
}

export function GetCurrentSyncJob(): $CancellablePromise<$models.SyncJobDTO> {
    return $Call.ByID(1063436565);
}

export function PreviewMarketDataSync(request: $models.SyncRequestDTO): $CancellablePromise<$models.SyncPlanPreviewDTO> {
    return $Call.ByID(844179907, request);
}

/**
 * ScanMarketDataHealth runs the local Data Health scan. Opening Data Health
 * must not cause provider HTTP; this method only reads the database, local
 * Tiingo key status, and in-process job snapshot.
 */
export function ScanMarketDataHealth(): $CancellablePromise<$models.MarketDataHealthReportDTO> {
    return $Call.ByID(247455835);
}

/**
 * SearchInstruments routes stock/ETF and crypto searches to their providers.
 * It is a form-assist read and does not persist anything.
 */
export function SearchInstruments(query: string, instrumentType: string): $CancellablePromise<$models.InstrumentSearchHitDTO[] | null> {
    return $Call.ByID(1127653350, query, instrumentType);
}

export function StartMarketDataSync(request: $models.SyncRequestDTO): $CancellablePromise<$models.SyncStartResultDTO> {
    return $Call.ByID(2978115899, request);
}

/**
 * StartRefreshAll launches RefreshAll in a goroutine and returns
 * immediately; completion is reported via RefreshCompletedEvent.
 */
export function StartRefreshAll(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(2865998654, requestID);
}

export function StartRefreshFX(requestID: string, currencyA: string, currencyB: string): $CancellablePromise<void> {
    return $Call.ByID(225720237, requestID, currencyA, currencyB);
}

export function StartRefreshInstrument(requestID: string, instrumentID: string): $CancellablePromise<void> {
    return $Call.ByID(1426013942, requestID, instrumentID);
}

export function StartRefreshMissingOrStale(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(4113174669, requestID);
}
