// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelAllAndWait(): $CancellablePromise<void> {
    return $Call.ByID(714817123);
}

/**
 * CancelRefresh cancels the in-flight refresh started under requestID, if
 * any, and emits a cancelled completion event. Calling it for an unknown or
 * already-completed requestID is a no-op, not an error: the frontend does not
 * need to race its own completion event to decide whether cancellation is
 * still meaningful.
 */
export function CancelRefresh(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(2389924325, requestID);
}

export function CancelSyncJob(jobID: string): $CancellablePromise<$models.SyncJobDTO> {
    return $Call.ByID(1970761316, jobID);
}

export function FXProviderKey(): $CancellablePromise<string> {
    return $Call.ByID(196886086);
}

export function GetCurrentSyncJob(): $CancellablePromise<$models.SyncJobDTO> {
    return $Call.ByID(1063436565);
}

export function GetSyncJob(jobID: string): $CancellablePromise<$models.SyncJobDTO> {
    return $Call.ByID(785822122, jobID);
}

export function PreviewMarketDataSync(request: $models.SyncRequestDTO): $CancellablePromise<$models.SyncPlanPreviewDTO> {
    return $Call.ByID(844179907, request);
}

export function RefreshAll(): $CancellablePromise<$models.RefreshResultDTO> {
    return $Call.ByID(929934818);
}

export function RefreshFX(currencyA: string, currencyB: string): $CancellablePromise<$models.RefreshResultDTO> {
    return $Call.ByID(1061472273, currencyA, currencyB);
}

export function RefreshInstrument(instrumentID: string): $CancellablePromise<$models.RefreshResultDTO> {
    return $Call.ByID(2683911434, instrumentID);
}

export function RefreshMissingOrStale(): $CancellablePromise<$models.RefreshResultDTO> {
    return $Call.ByID(3219501745);
}

export function RefreshRequiredFX(): $CancellablePromise<$models.RefreshResultDTO> {
    return $Call.ByID(1206509500);
}

export function SetFXProvider(key: string): $CancellablePromise<void> {
    return $Call.ByID(758763431, key);
}

export function StartMarketDataSync(request: $models.SyncRequestDTO): $CancellablePromise<$models.SyncStartResultDTO> {
    return $Call.ByID(2978115899, request);
}

/**
 * StartRefreshAll launches RefreshAll in a goroutine and returns
 * immediately; completion is reported via RefreshCompletedEvent.
 */
export function StartRefreshAll(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(2865998654, requestID);
}

export function StartRefreshFX(requestID: string, currencyA: string, currencyB: string): $CancellablePromise<void> {
    return $Call.ByID(225720237, requestID, currencyA, currencyB);
}

export function StartRefreshInstrument(requestID: string, instrumentID: string): $CancellablePromise<void> {
    return $Call.ByID(1426013942, requestID, instrumentID);
}

export function StartRefreshMissingOrStale(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(4113174669, requestID);
}

export function StartRefreshRequiredFX(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(1828580296, requestID);
}
