// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

/**
 * NetWorthTrendDTO mirrors domain.NetWorthTrend.
 */
export interface NetWorthTrendDTO {
    "range": string;
    "currency": string;
    "points": NetWorthTrendPointDTO[] | null;
    "start"?: wire$0.SignedMoneyView | null;
    "end"?: wire$0.SignedMoneyView | null;
    "change"?: wire$0.SignedMoneyView | null;
}

/**
 * NetWorthTrendPointDTO mirrors domain.NetWorthTrendPoint.
 */
export interface NetWorthTrendPointDTO {
    "localDate": string;
    "netWorth"?: wire$0.SignedMoneyView | null;
    "assets"?: wire$0.MoneyView | null;
    "liabilities"?: wire$0.MoneyView | null;
    "status": string;
    "complete": boolean;
    "missingCount": number;
}

/**
 * OverviewDTO mirrors domain.OverviewResult.
 */
export interface OverviewDTO {
    "currency": string;
    "accountCount": number;
    "complete": boolean;
    "missingInputs": wire$0.MissingInputDTO[] | null;
    "assets": string;
    "liabilities": string;
    "netWorth": string;
    "assetsByType": wire$0.BreakdownDTO[] | null;
    "liabilitiesByType": wire$0.BreakdownDTO[] | null;
    "byMember": wire$0.BreakdownDTO[] | null;
    "byInstitution": wire$0.BreakdownDTO[] | null;
    "byGroup": wire$0.BreakdownDTO[] | null;
    "byAccountType": wire$0.BreakdownDTO[] | null;
    "historyStarted": boolean;
    "recentActivities": wire$0.ActivityDTO[] | null;
    "accountLabels": OverviewNamedDTO[] | null;
    "instrumentLabels": OverviewInstrumentLabelDTO[] | null;
    "holdingLabels": OverviewHoldingLabelDTO[] | null;
}

export interface OverviewHoldingLabelDTO {
    "id": string;
    "accountId": string;
    "instrumentId": string;
    "name": string;
}

export interface OverviewInstrumentLabelDTO {
    "id": string;
    "name": string;
    "quoteSource"?: string;
}

export interface OverviewNamedDTO {
    "id": string;
    "name": string;
}

/**
 * PortfolioDTO mirrors domain.PortfolioValuation.
 */
export interface PortfolioDTO {
    "currency": string;
    "valuedSubtotal"?: wire$0.MoneyView | null;
    "complete": boolean;
    "accounts": wire$0.AccountValuationDTO[] | null;
    "missingInputs": wire$0.MissingInputDTO[] | null;
    "byCurrency": wire$0.AllocationDTO[] | null;
    "byCountry": wire$0.AllocationDTO[] | null;
    "byInstrumentType": wire$0.AllocationDTO[] | null;
}

/**
 * PortfolioTrendDTO mirrors domain.PortfolioTrend.
 */
export interface PortfolioTrendDTO {
    "range": string;
    "currency": string;
    "points": PortfolioTrendPointDTO[] | null;
}

/**
 * PortfolioTrendPointDTO mirrors domain.PortfolioTrendPoint.
 */
export interface PortfolioTrendPointDTO {
    "localDate": string;
    "valuedSubtotal"?: wire$0.MoneyView | null;
    "status": string;
    "complete": boolean;
    "missingCount": number;
}
