// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as account$0 from "../account/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function NetWorthTrend(trendRange: string): $CancellablePromise<$models.NetWorthTrendDTO> {
    return $Call.ByID(3771424334, trendRange);
}

export function Overview(request: account$0.AccountFilterRequest): $CancellablePromise<$models.OverviewDTO> {
    return $Call.ByID(3181417489, request);
}

export function Portfolio(request: account$0.AccountFilterRequest): $CancellablePromise<$models.PortfolioDTO> {
    return $Call.ByID(3154183370, request);
}

export function PortfolioTrend(trendRange: string): $CancellablePromise<$models.PortfolioTrendDTO> {
    return $Call.ByID(3844706429, trendRange);
}
