// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

export interface AppendProductValuationRequest {
    "productId": string;
    "amount": string;
    "observedAt": string;
    "mutationId": string;
}

export interface BucketResultDTO {
    "horizonOn": string;
    "selectedRoute": RouteDTO | null;
    "netNative": wire$0.MoneyView | null;
    "netBase": wire$0.MoneyView | null;
    "appliedReserveNative": wire$0.MoneyView | null;
    "unreservedNative": wire$0.MoneyView | null;
    "reserveShortfallNative": wire$0.MoneyView | null;
    "status": string;
    "reasons": string[] | null;
}

export interface LiquidityBucketDTO {
    "horizonOn": string;
    "status": string;
    "fullAvailable": wire$0.MoneyView | null;
    "knownAvailableSubtotal": wire$0.MoneyView | null;
    "appliedReserveSubtotal": wire$0.MoneyView | null;
    "fullUnreserved": wire$0.MoneyView | null;
    "knownUnreservedSubtotal": wire$0.MoneyView | null;
    "unknownSourceCount": number;
    "excludedSourceCount": number;
    "estimatedSourceCount": number;
    "nativeCurrencyGroups": NativeCurrencyGroupDTO[] | null;
    "warnings": string[] | null;
}

export interface LiquidityOverviewDTO {
    "asOf": string;
    "localDate": string;
    "timezone": string;
    "baseCurrency": string;
    "assumptions": string[] | null;
    "buckets": LiquidityBucketDTO[] | null;
    "sources": LiquiditySourceDTO[] | null;
    "unresolvedReservations": UnresolvedReservationDTO[] | null;
}

export interface LiquiditySourceDTO {
    "sourceRef": SourceRefDTO;
    "sourceKey": string;
    "accountId": string;
    "productId": string | null;
    "displayName": string;
    "nativeCurrency": string;
    "currentNativeValue": wire$0.MoneyView | null;
    "valueAsOf": string | null;
    "priceEvidence": wire$0.QuoteEvidenceDTO | null;
    "fxEvidence": wire$0.QuoteEvidenceDTO | null;
    "policyOrigin": string;
    "policy": PolicyDTO | null;
    "contractState": string | null;
    "displayState": string;
    "reservationRequested": wire$0.MoneyView;
    "normalRoute": RouteDTO | null;
    "earlyRoute": RouteDTO | null;
    "bucketResults": BucketResultDTO[] | null;
    "reasons": string[] | null;
    "assumptions": string[] | null;
    "excluded": boolean;
    "dueUnconfirmed": boolean;
}

export interface ListOperationsRequest {
    "productId": string;
    "cursor"?: string;
    "limit"?: number;
}

export interface ListProductsRequest {
    "accountId"?: string | null;
    "includeClosed": boolean;
}

export interface NativeCurrencyGroupDTO {
    "currency": string;
    "status": string;
    "fullAvailable": wire$0.MoneyView | null;
    "knownAvailableSubtotal": wire$0.MoneyView | null;
    "appliedReserveSubtotal": wire$0.MoneyView | null;
    "fullUnreserved": wire$0.MoneyView | null;
    "knownUnreservedSubtotal": wire$0.MoneyView | null;
}

export interface OverviewRequest {
    "customHorizonOn"?: string | null;
    "includeEarlyWithdrawal": boolean;
}

export interface PolicyDTO {
    "id": string;
    "sourceRef": SourceRefDTO;
    "accessKind": string;
    "unlockOn": string | null;
    "settlementDays": number | null;
    "dayBasis": string | null;
    "receiptOnOverride": string | null;
    "accessibleAmountCap": wire$0.MoneyView | null;
    "normalExitFee": wire$0.MoneyView | null;
    "earlyKind": string;
    "earlySettlementDays": number | null;
    "earlyDayBasis": string | null;
    "earlyFee": wire$0.MoneyView | null;
    "earlyAmountMode": string | null;
    "earlyGrossAmount": wire$0.MoneyView | null;
    "confirmedAt": string | null;
    "note": string | null;
    "revision": number;
}

/**
 * ProductCommandRequest is the tagged union the frontend submits for every
 * product lifecycle action. Exactly one payload must match Kind.
 */
export interface ProductCommandRequest {
    "kind": string;
    "open"?: application$0.OpenProductCommand | null;
    "recordExisting"?: application$0.RecordExistingProductCommand | null;
    "receiveInterest"?: application$0.ReceiveInterestCommand | null;
    "settle"?: application$0.SettleProductCommand | null;
    "renew"?: application$0.RenewProductCommand | null;
    "undo"?: application$0.UndoProductCommand | null;
}

export interface ProductDTO {
    "id": string;
    "accountId": string;
    "holdingId": string;
    "instrumentId": string;
    "kind": string;
    "name": string;
    "note": string | null;
    "currency": string;
    "principal": wire$0.MoneyView;
    "currentValue": wire$0.MoneyView | null;
    "currentCostBasis": wire$0.MoneyView | null;
    "startOn": string;
    "maturityOn": string | null;
    "interestMode": string;
    "annualRate": string | null;
    "maturityInterest": wire$0.MoneyView | null;
    "interestPaidThroughOn": string | null;
    "state": string;
    "displayState": string;
    "policy": PolicyDTO;
    "revision": number;
    "predecessorId": string | null;
    "successorId": string | null;
    "nextAction": string;
}

export interface ProductDetailDTO {
    "product": ProductDTO;
    "reservations": ReservationDTO[] | null;
    "permittedActions": string[] | null;
    "disabledReasons": { [_ in string]?: string } | null;
}

export interface ProductOperationDTO {
    "id": string;
    "kind": string;
    "effectiveAt": string;
    "createdAt": string;
    "reversesOperationId": string | null;
}

export interface ProductOperationPageDTO {
    "operations": ProductOperationDTO[] | null;
    "next": string | null;
}

export interface ProductOperationPreviewDTO {
    "effectiveAt": string;
    "netWorthDelta": wire$0.SignedMoneyView | null;
    "reservationReleaseDetails": ReservationDTO[] | null;
    "kind": string;
    "normalizedJson": string;
    "payloadSha256": string;
    "reviewedStateHash": string;
    "localDate": string;
    "timezone": string;
    "warnings": string[] | null;
    "assumptions": string[] | null;
    "missingFields": string[] | null;
    "activities": wire$0.ChangePreviewDTO[] | null;
    "cashBefore": wire$0.MoneyView[] | null;
    "cashAfter": wire$0.MoneyView[] | null;
    "productBefore": wire$0.MoneyView | null;
    "productAfter": wire$0.MoneyView | null;
    "netWorthKnown": boolean;
    "reservationReleases": string[] | null;
    "draftProductIds": string[] | null;
}

export interface ProductOperationReceiptDTO {
    "operationId": string;
    "kind": string;
    "productIds": string[] | null;
    "activityIds": string[] | null;
    "quoteIds": string[] | null;
    "cashAfter": wire$0.MoneyView[] | null;
    "replayed": boolean;
    "createdAt": string;
}

export interface RecordProductOperationRequest {
    "command": ProductCommandRequest;
    "mutationId": string;
    "reviewedStateHash": string;
}

export interface ReleaseReservationRequest {
    "id": string;
    "expectedRevision": number;
}

export interface ReservationDTO {
    "id": string;
    "sourceRef": SourceRefDTO;
    "label": string;
    "amount": wire$0.MoneyView;
    "currency": string;
    "revision": number;
    "createdAt": string;
    "updatedAt": string;
    "releasedAt": string | null;
}

export interface ResetPolicyRequest {
    "sourceRef": SourceRefDTO;
    "expectedRevision": number;
}

export interface RouteDTO {
    "kind": string;
    "eligibleOn": string | null;
    "receiptOn": string | null;
    "grossNative": wire$0.MoneyView | null;
    "feeNative": wire$0.MoneyView | null;
    "netNative": wire$0.MoneyView | null;
    "status": string;
    "amountBasis": string;
    "actionRequired": string;
    "assumptions": string[] | null;
    "missingReasons": string[] | null;
}

export interface SavePolicyRequest {
    "sourceRef": SourceRefDTO;
    "expectedRevision": number;
    "policy": application$0.ProductPolicyInput;
}

export interface SaveReservationRequest {
    "id"?: string | null;
    "sourceRef": SourceRefDTO;
    "expectedRevision": number;
    "label": string;
    "amount": string;
}

export interface SourceRefDTO {
    "kind": string;
    "accountId": string;
    "holdingId"?: string | null;
    "currency"?: string | null;
}

export interface UnresolvedReservationDTO {
    "reservation": ReservationDTO;
    "reason": string;
}

export interface UpdateProductTermsRequest {
    "productId": string;
    "expectedRevision": number;
    "terms": application$0.ProductTermsInput;
    "policy": application$0.ProductPolicyInput;
}
