// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppendProductValuation(request: $models.AppendProductValuationRequest): $CancellablePromise<$models.ProductDetailDTO> {
    return $Call.ByID(1249349732, request);
}

export function ListOperations(request: $models.ListOperationsRequest): $CancellablePromise<$models.ProductOperationPageDTO> {
    return $Call.ByID(3130043868, request);
}

export function ListProducts(request: $models.ListProductsRequest): $CancellablePromise<$models.ProductDetailDTO[] | null> {
    return $Call.ByID(841124278, request);
}

export function ListReservations(): $CancellablePromise<$models.ReservationDTO[] | null> {
    return $Call.ByID(2217556709);
}

export function Overview(request: $models.OverviewRequest): $CancellablePromise<$models.LiquidityOverviewDTO> {
    return $Call.ByID(1188744533, request);
}

export function PreviewProductOperation(request: $models.ProductCommandRequest): $CancellablePromise<$models.ProductOperationPreviewDTO> {
    return $Call.ByID(2882180826, request);
}

export function Product(productID: string): $CancellablePromise<$models.ProductDetailDTO> {
    return $Call.ByID(3264911885, productID);
}

export function RecordProductOperation(request: $models.RecordProductOperationRequest): $CancellablePromise<$models.ProductOperationReceiptDTO> {
    return $Call.ByID(416110975, request);
}

export function ReleaseReservation(request: $models.ReleaseReservationRequest): $CancellablePromise<$models.ReservationDTO> {
    return $Call.ByID(2536970071, request);
}

export function ResetPolicy(request: $models.ResetPolicyRequest): $CancellablePromise<$models.PolicyDTO> {
    return $Call.ByID(2901917459, request);
}

export function SavePolicy(request: $models.SavePolicyRequest): $CancellablePromise<$models.PolicyDTO> {
    return $Call.ByID(3024543733, request);
}

export function SaveReservation(request: $models.SaveReservationRequest): $CancellablePromise<$models.ReservationDTO> {
    return $Call.ByID(1286965555, request);
}

export function UpdateProductTerms(request: $models.UpdateProductTermsRequest): $CancellablePromise<$models.ProductDetailDTO> {
    return $Call.ByID(2912879229, request);
}
