// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CreateHoldingRequest mirrors application.HoldingInput.
 */
export interface CreateHoldingRequest {
    "accountId": string;
    "instrumentId": string;
    "quantity": string;
    "unitCost"?: string;
    "note"?: string | null;
    "sortOrder"?: number;
}

/**
 * UpdateHoldingRequest is the metadata-only update contract. Quantity is
 * intentionally absent: financial quantity changes use the dedicated
 * pre-history compatibility method or HistoryService.RecordChange.
 */
export interface UpdateHoldingRequest {
    "note"?: string | null;
    "noteSet"?: boolean;
    "sortOrder"?: number;
    "sortOrderSet"?: boolean;
}
