// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendAccountCashValue is the cash baseline/import entry point before
 * history starts. After history starts, application.Service translates the
 * requested resulting balance into a reconciliation cash_in/cash_out and
 * commits it through the same PreviewChange/RecordChange engine; it does not
 * create a second persistence path.
 */
export function AppendAccountCashValue(accountID: string, amount: string, currency: string, effectiveAt: string): $CancellablePromise<wire$0.AccountCashValueDTO> {
    return $Call.ByID(2810686086, accountID, amount, currency, effectiveAt);
}

export function ArchiveHolding(id: string, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(2096620566, id, archived);
}

export function CreateHolding(request: $models.CreateHoldingRequest): $CancellablePromise<wire$0.HoldingDTO> {
    return $Call.ByID(1487305998, request);
}

/**
 * HoldingsByAccounts loads holdings for several accounts in one call,
 * returned as a map keyed by account ID string (JSON object keys must be
 * strings; domain.AccountID already is one).
 */
export function HoldingsByAccounts(accountIDs: string[] | null): $CancellablePromise<{ [_ in string]?: wire$0.HoldingDTO[] | null } | null> {
    return $Call.ByID(756240794, accountIDs);
}

export function ListAccountCashValues(accountID: string): $CancellablePromise<wire$0.AccountCashValueDTO[] | null> {
    return $Call.ByID(28387767, accountID);
}

export function ListHoldings(accountID: string, includeArchived: boolean): $CancellablePromise<wire$0.HoldingDTO[] | null> {
    return $Call.ByID(1117849871, accountID, includeArchived);
}

export function UpdateHolding(id: string, request: $models.UpdateHoldingRequest): $CancellablePromise<wire$0.HoldingDTO> {
    return $Call.ByID(4282570637, id, request);
}

/**
 * UpdateHoldingQuantity is retained for pre-history compatibility only; once
 * history has started, the application layer rejects it and the frontend
 * must use HistoryService.RecordChange with a position adjustment.
 * Deprecated: use HistoryService.RecordChange after history starts.
 */
export function UpdateHoldingQuantity(id: string, quantity: string): $CancellablePromise<wire$0.HoldingDTO> {
    return $Call.ByID(758418768, id, quantity);
}
