// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

/**
 * BootstrapResult mirrors application.Bootstrap. Household is nil until
 * onboarding completes; the frontend uses its presence to decide whether to
 * show the Onboarding flow or the main application shell.
 */
export interface BootstrapResult {
    "household": wire$0.HouseholdDTO | null;
    "members": wire$0.MemberDTO[] | null;
    "institutions": wire$0.InstitutionDTO[] | null;
    "groups": wire$0.GroupDTO[] | null;
}

/**
 * CompleteOnboardingRequest is the Onboarding form's submitted shape. An
 * empty Timezone means "history not started yet".
 */
export interface CompleteOnboardingRequest {
    "householdName": string;
    "baseCurrency": string;
    "memberNames": string[] | null;
    "timezone"?: string;
}
