// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is registered with application.NewService in the Wails main.go.
 * It depends only on internal/application, never on internal/infrastructure
 * or the Wails runtime.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bootstrap loads the current Household plus its active Members,
 * Institutions, and Groups in one call.
 */
export function Bootstrap(): $CancellablePromise<$models.BootstrapResult> {
    return $Call.ByID(3178430509);
}

/**
 * CompleteOnboarding creates the singleton Household, its base currency,
 * and its first Members. It fails with domain.ErrConflict if a Household
 * already exists.
 */
export function CompleteOnboarding(request: $models.CompleteOnboardingRequest): $CancellablePromise<void> {
    return $Call.ByID(2679881179, request);
}
