// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstrumentRequest mirrors application.InstrumentInput. Replace=true means
 * "this is the complete form state" (matches InstrumentInput.Replace); when
 * false and used for an update, zero-valued fields keep the current value.
 */
export interface InstrumentRequest {
    "replace"?: boolean;
    "name": string;
    "type": string;
    "quoteCurrency": string;
    "symbol"?: string | null;
    "marketCode"?: string | null;
    "countryCode"?: string | null;
    "isin"?: string | null;
    "note"?: string | null;
    "iconKey"?: string | null;
    "sortOrder"?: number;
    "quoteSource"?: string;
    "providerKey"?: string | null;
    "providerSymbol"?: string | null;
}
