// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ArchiveInstrument(id: string, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(1418357486, id, archived);
}

export function CreateInstrument(request: $models.InstrumentRequest): $CancellablePromise<wire$0.InstrumentDTO> {
    return $Call.ByID(1003083542, request);
}

export function ListInstruments(includeArchived: boolean): $CancellablePromise<wire$0.InstrumentDTO[] | null> {
    return $Call.ByID(3717597159, includeArchived);
}

export function SetInstrumentIcon(id: string, iconKey: string): $CancellablePromise<void> {
    return $Call.ByID(3109919373, id, iconKey);
}

export function SetInstrumentQuoteSource(id: string, source: string): $CancellablePromise<void> {
    return $Call.ByID(2859585421, id, source);
}

export function UpdateInstrument(id: string, request: $models.InstrumentRequest): $CancellablePromise<wire$0.InstrumentDTO> {
    return $Call.ByID(3318596211, id, request);
}
