// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcpserver$0 from "../../mcpserver/models.js";

export function Connection(): $CancellablePromise<mcpserver$0.Connection> {
    return $Call.ByID(633861421);
}

export function Disable(): $CancellablePromise<mcpserver$0.Status> {
    return $Call.ByID(4084108143);
}

export function Enable(mode: string): $CancellablePromise<mcpserver$0.Status> {
    return $Call.ByID(676857466, mode);
}

export function RecentOperations(): $CancellablePromise<mcpserver$0.OperationSummary[] | null> {
    return $Call.ByID(3976018212);
}

export function Status(): $CancellablePromise<mcpserver$0.Status> {
    return $Call.ByID(1887009171);
}
