package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/shopspring/decimal"
	"github.com/waltwang/nestworth-go/internal/application"
	"github.com/waltwang/nestworth-go/internal/domain"
	"github.com/waltwang/nestworth-go/internal/infrastructure/sqlite"
)

type residualOut struct {
	DBPath               string        `json:"dbPath"`
	Injection            bool          `json:"injection"`
	CorruptDay           string        `json:"corruptDay"`
	ItemID               string        `json:"itemId"`
	HoldingID            string        `json:"holdingId"`
	BaseBefore           string        `json:"baseBefore"`
	BaseAfter            string        `json:"baseAfter"`
	NativeUnchanged      string        `json:"nativeUnchanged"`
	ExpectedResidual     string        `json:"expectedResidualApprox"`
	RevisionAfter        int           `json:"revisionAfter"`
	From                 string        `json:"from"`
	To                   string        `json:"to"`
	AssetChangeAvail     bool          `json:"assetChangeAvailable"`
	ResidualIssueCount   int           `json:"residualIssueCount"`
	WaterfallResidual    *co03Money    `json:"waterfallResidual,omitempty"`
	DriverDetailCount    int           `json:"driverDetailCount"`
	DriverDetails        []residualDet `json:"driverDetails"`
	DayComponentResidual *co03Money    `json:"dayComponentResidual,omitempty"`
	DayStatus            string        `json:"dayStatus,omitempty"`
	UnexplainedPositive  bool          `json:"unexplainedPositive"`
	PASS                 bool          `json:"pass"`
	Detail               string        `json:"detail"`
	Error                string        `json:"error,omitempty"`
}

type residualDet struct {
	Date         string     `json:"date"`
	ComponentKey string     `json:"componentKey"`
	AccountID    string     `json:"accountId,omitempty"`
	HoldingID    string     `json:"holdingId,omitempty"`
	InstrumentID string     `json:"instrumentId,omitempty"`
	Amount       *co03Money `json:"amount,omitempty"`
}

func runResidualProbe() error {
	sourceDBPath := envOr("NESTWORTH_RESIDUAL_SOURCE_DB", envOr("NESTWORTH_DATABASE_PATH", "/workspace/nestworth-analytics-qa/data/nestworth.db"))
	outPath := envOr("NESTWORTH_PROBE_OUT", "/workspace/nestworth-analytics-qa/seed/probe-residual.json")
	logPath := envOr("NESTWORTH_PROBE_LOG", "/workspace/nestworth-analytics-qa/logs/12-residual.log")
	dbPath := envOr("NESTWORTH_RESIDUAL_WORK_DB", filepath.Join(filepath.Dir(outPath), "residual-corrupt.db"))
	corruptDay := envOr("NESTWORTH_RESIDUAL_DAY", "2026-08-12")
	inject := envOr("NESTWORTH_RESIDUAL_INJECT", "true") != "false"
	from := envOr("NESTWORTH_PROBE_FROM", "2026-08-01")
	to := envOr("NESTWORTH_PROBE_TO", "2026-09-07")

	out := residualOut{
		DBPath: dbPath, Injection: inject, CorruptDay: corruptDay, From: from, To: to,
		ItemID:           envOr("NESTWORTH_RESIDUAL_ITEM_ID", ""),
		HoldingID:        envOr("NESTWORTH_RESIDUAL_HOLDING_ID", ""),
		BaseBefore:       envOr("NESTWORTH_RESIDUAL_BASE_BEFORE", ""),
		ExpectedResidual: envOr("NESTWORTH_RESIDUAL_EXPECTED", "100"),
	}

	if filepath.Clean(sourceDBPath) == filepath.Clean(dbPath) {
		out.Error = "residual source and work database must be different"
		return writeResidual(outPath, logPath, out)
	}
	if err := copySQLiteDatabase(sourceDBPath, dbPath); err != nil {
		out.Error = "copy residual source database: " + err.Error()
		return writeResidual(outPath, logPath, out)
	}
	database, err := sqlite.Open(dbPath)
	if err != nil {
		out.Error = err.Error()
		return writeResidual(outPath, logPath, out)
	}
	defer database.Close()

	// Resolve the corrupted item from the fixture itself. IDs are generated by
	// the seed and must not be copied from one run into the next.
	if out.ItemID == "" {
		row := database.SQL.QueryRow(`SELECT i.id, COALESCE(i.holding_id, ''), i.base_amount, i.native_amount
			FROM daily_valuation_snapshot_items i
			JOIN daily_valuation_snapshots s ON s.id = i.snapshot_id
			WHERE s.local_date = ? AND i.holding_id IS NOT NULL
			ORDER BY s.revision DESC, i.id LIMIT 1`, corruptDay)
		if err := row.Scan(&out.ItemID, &out.HoldingID, &out.BaseBefore, &out.NativeUnchanged); err != nil {
			out.Error = "corrupt item lookup: " + err.Error()
			return writeResidual(outPath, logPath, out)
		}
	} else if out.HoldingID == "" {
		if err := database.SQL.QueryRow(`SELECT COALESCE(holding_id, '') FROM daily_valuation_snapshot_items WHERE id = ?`, out.ItemID).Scan(&out.HoldingID); err != nil {
			out.Error = "holding lookup: " + err.Error()
			return writeResidual(outPath, logPath, out)
		}
	}

	// Apply a deliberate +100 base-only corruption to a copied database. The
	// source fixture is never mutated, while the native amount remains intact.
	var base, native string
	var rev int
	row := database.SQL.QueryRow(`SELECT i.base_amount, i.native_amount, s.revision
		FROM daily_valuation_snapshot_items i
		JOIN daily_valuation_snapshots s ON s.id=i.snapshot_id
		WHERE i.id=?`, out.ItemID)
	if err := row.Scan(&base, &native, &rev); err != nil {
		out.Error = "corrupt item lookup: " + err.Error()
		return writeResidual(outPath, logPath, out)
	}
	if out.BaseBefore == "" {
		out.BaseBefore = base
	}
	if out.NativeUnchanged == "" {
		out.NativeUnchanged = native
	}
	expected, parseErr := decimal.NewFromString(out.ExpectedResidual)
	if parseErr != nil || !expected.IsPositive() {
		out.Error = "expected residual must be a positive decimal"
		return writeResidual(outPath, logPath, out)
	}
	if inject {
		before, parseErr := decimal.NewFromString(base)
		if parseErr != nil {
			out.Error = "parse base amount: " + parseErr.Error()
			return writeResidual(outPath, logPath, out)
		}
		corrupted := before.Add(expected)
		if _, err := database.SQL.Exec(`UPDATE daily_valuation_snapshot_items SET base_amount = ? WHERE id = ?`, corrupted.String(), out.ItemID); err != nil {
			out.Error = "apply residual corruption: " + err.Error()
			return writeResidual(outPath, logPath, out)
		}
	}
	if err := database.SQL.QueryRow(`SELECT base_amount, native_amount FROM daily_valuation_snapshot_items WHERE id = ?`, out.ItemID).Scan(&out.BaseAfter, &native); err != nil {
		out.Error = "read corrupted item: " + err.Error()
		return writeResidual(outPath, logPath, out)
	}
	if native != out.NativeUnchanged {
		out.Error = fmt.Sprintf("native amount changed during corruption: before=%s after=%s", out.NativeUnchanged, native)
		return writeResidual(outPath, logPath, out)
	}
	out.RevisionAfter = rev

	svc := application.NewService(sqlite.NewRepository(database))
	ctx := context.Background()
	query := domain.AnalysisQuery{
		Scope: domain.AnalysisScope{Kind: domain.ScopeHousehold},
		From:  from, To: to,
		Valuation: domain.ValuationBase, IncludeCash: true, Basis: domain.ReturnBasisInvestment,
	}

	change, err := svc.AssetChange(ctx, query)
	if err != nil {
		out.Error = "AssetChange: " + err.Error()
		return writeResidual(outPath, logPath, out)
	}
	out.AssetChangeAvail = change.Available
	out.ResidualIssueCount = change.ResidualIssueCount
	for _, row := range change.Waterfall {
		if row.Bucket == domain.BucketResidual && row.Amount != nil {
			out.WaterfallResidual = moneyOutCo03(row.Amount)
		}
	}

	detail, err := svc.AssetDriverDetail(ctx, query, string(domain.BucketResidual))
	if err != nil {
		out.Error = "AssetDriverDetail: " + err.Error()
		return writeResidual(outPath, logPath, out)
	}
	out.DriverDetailCount = len(detail.ResidualDetails)
	for _, d := range detail.ResidualDetails {
		out.DriverDetails = append(out.DriverDetails, residualDet{
			Date: string(d.Date), ComponentKey: d.ComponentKey,
			AccountID: d.AccountID, HoldingID: d.HoldingID, InstrumentID: d.InstrumentID,
			Amount: moneyOutCo03(d.Amount),
		})
	}

	// Also inspect Analyze day for the corrupt local date
	result, err := svc.Analyze(ctx, query)
	if err != nil {
		out.Error = "Analyze: " + err.Error()
		return writeResidual(outPath, logPath, out)
	}
	for _, day := range result.Days {
		if string(day.Date) != corruptDay {
			continue
		}
		if day.Component.HoldingID == nil || day.Component.HoldingID.String() != out.HoldingID {
			continue
		}
		out.DayStatus = string(day.Status)
		if day.Residual != nil {
			out.DayComponentResidual = moneyOutCo03(&day.Residual.Amount)
		} else if v, ok := day.AssetBuckets[domain.BucketResidual]; ok && v.Currency() != "" {
			out.DayComponentResidual = &co03Money{Amount: v.CanonicalAmount(), Currency: v.Currency().String()}
		}
	}

	residualAmt := decimal.Zero
	if out.WaterfallResidual != nil {
		residualAmt, _ = decimal.NewFromString(out.WaterfallResidual.Amount)
	}
	dayAmt := decimal.Zero
	if out.DayComponentResidual != nil {
		dayAmt, _ = decimal.NewFromString(out.DayComponentResidual.Amount)
	}
	out.UnexplainedPositive = residualAmt.IsPositive() || dayAmt.IsPositive() || out.ResidualIssueCount > 0
	if inject {
		out.PASS = out.UnexplainedPositive && (dayAmt.Abs().GreaterThan(expected.Div(decimal.NewFromInt(2))) || residualAmt.Abs().GreaterThan(expected.Div(decimal.NewFromInt(2))))
		out.Detail = fmt.Sprintf("deliberate +%s AUD base corruption on holding item %s local=%s; expected residual≈%s; waterfall=%v day=%v issues=%d",
			expected, out.ItemID, corruptDay, expected, out.WaterfallResidual, out.DayComponentResidual, out.ResidualIssueCount)
	} else {
		out.PASS = !out.UnexplainedPositive && out.ResidualIssueCount == 0
		out.Detail = fmt.Sprintf("clean copied fixture local=%s; expected no residual; waterfall=%v day=%v issues=%d",
			corruptDay, out.WaterfallResidual, out.DayComponentResidual, out.ResidualIssueCount)
	}

	return writeResidual(outPath, logPath, out)
}

func copySQLiteDatabase(source, target string) error {
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	for _, suffix := range []string{"", "-wal", "-shm"} {
		sourcePath, targetPath := source+suffix, target+suffix
		data, err := os.ReadFile(sourcePath)
		if err != nil {
			if os.IsNotExist(err) {
				_ = os.Remove(targetPath)
				continue
			}
			return err
		}
		if err := os.WriteFile(targetPath, data, 0o600); err != nil {
			return err
		}
	}
	return nil
}

func writeResidual(outPath, logPath string, out residualOut) error {
	raw, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, raw, 0o644); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("§17.4 Deliberate Residual probe\n")
	b.WriteString("================================\n")
	b.Write(raw)
	b.WriteString("\n\nSUMMARY\n")
	fmt.Fprintf(&b, "pass=%v unexplainedPositive=%v corruptDay=%s expected≈%s\n", out.PASS, out.UnexplainedPositive, out.CorruptDay, out.ExpectedResidual)
	fmt.Fprintf(&b, "waterfallResidual=%v dayResidual=%v residualIssueCount=%d\n", out.WaterfallResidual, out.DayComponentResidual, out.ResidualIssueCount)
	fmt.Fprintf(&b, "detail=%s\n", out.Detail)
	if out.Error != "" {
		fmt.Fprintf(&b, "error=%s\n", out.Error)
	}
	if err := os.MkdirAll(filepath.Dir(logPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(logPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Print(b.String())
	return nil
}
