// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../settings/models.js";

/**
 * SettingsDTO is the Wails wire contract. The persisted settings.Settings
 * struct intentionally keeps its snake_case JSON tags for the on-disk format;
 * it must not leak into IPC or force the frontend to maintain two key shapes.
 */
export interface SettingsDTO {
    "schemaVersion": number;
    "appearance": settings$0.Appearance;
    "accent": settings$0.Accent;
    "language": settings$0.Language;
    "timezone": string;
    "weekStart": string;
    "dateFormat": string;
    "timeFormat": string;
    "currency": string;
    "decimalSeparator": string;
    "groupingSeparator": string;
    "decimalPlaces": number;
    "windowWidth": number;
    "windowHeight": number;
    "fxProvider": string;
    "quoteCacheTTL": string;
}

/**
 * TiingoKeyStatusDTO exposes only whether a locally configured key exists. The
 * key itself never crosses the Wails boundary.
 */
export interface TiingoKeyStatusDTO {
    "configured": boolean;
}
