// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CoinGeckoKeyStatus(): $CancellablePromise<$models.CoinGeckoKeyStatusDTO> {
    return $Call.ByID(4152863214);
}

export function DeleteCoinGeckoAPIKey(): $CancellablePromise<$models.CoinGeckoKeyStatusDTO> {
    return $Call.ByID(1447707263);
}

export function DeleteTiingoAPIKey(): $CancellablePromise<$models.TiingoKeyStatusDTO> {
    return $Call.ByID(2287834341);
}

export function DeleteWorkerAPIToken(): $CancellablePromise<$models.WorkerTokenStatusDTO> {
    return $Call.ByID(3907537255);
}

/**
 * FXProviders returns only registered providers that advertise latest-FX
 * support. Settings can therefore render the same closed list the
 * application routing layer can actually resolve.
 */
export function FXProviders(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2653696533);
}

/**
 * Load returns the persisted preferences, or internal/settings' documented
 * defaults if none are saved yet or the saved file could not be fully
 * trusted (internal/settings.Store.Load already salvages individually
 * invalid fields rather than discarding the whole file).
 */
export function Load(): $CancellablePromise<$models.SettingsDTO> {
    return $Call.ByID(3744917947);
}

/**
 * Reset restores settings.Default(), applying the same FX-provider
 * delegation performed by Save.
 */
export function Reset(): $CancellablePromise<$models.SettingsDTO> {
    return $Call.ByID(1989397258);
}

export function Save(value: $models.SettingsDTO): $CancellablePromise<void> {
    return $Call.ByID(1850635862, value);
}

export function SaveCoinGeckoAPIKey(value: string): $CancellablePromise<$models.CoinGeckoKeyStatusDTO> {
    return $Call.ByID(1280655601, value);
}

export function SaveTiingoAPIKey(value: string): $CancellablePromise<$models.TiingoKeyStatusDTO> {
    return $Call.ByID(452299787, value);
}

export function SaveWorkerAPIToken(value: string): $CancellablePromise<$models.WorkerTokenStatusDTO> {
    return $Call.ByID(699901789, value);
}

/**
 * SupportedCurrencies returns the closed currency catalog from domain.
 */
export function SupportedCurrencies(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1124163240);
}

export function TiingoKeyStatus(): $CancellablePromise<$models.TiingoKeyStatusDTO> {
    return $Call.ByID(152636482);
}

export function WorkerTokenStatus(): $CancellablePromise<$models.WorkerTokenStatusDTO> {
    return $Call.ByID(1929683320);
}
