// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Connection {
    "endpoint": string;
    "token": string;
    "json": string;
}

export interface OperationSummary {
    "id": string;
    "tool": string;
    "status": string;
    "createdAt": string;
}

export interface Status {
    "running": boolean;
    "mode": string;
    "endpoint": string;
    "instanceId": string;
    "error"?: string;
}
