// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BackupResultDTO {
    "cancelled": boolean;
    "fileName"?: string;
    "createdAt"?: string;
    "schemaVersion"?: number;
    "appVersion"?: string;
    "appBuild"?: string;
    "accounts": number;
    "holdings": number;
    "activities": number;
    "verificationResult"?: string;
}

export interface BackupStatusDTO {
    "available": boolean;
    "backupFileName"?: string;
    "createdAt"?: string;
    "schemaVersion"?: number;
    "appVersion"?: string;
    "appBuild"?: string;
    "verificationResult"?: string;
}

export interface ExportResultDTO {
    "cancelled": boolean;
    "fileName"?: string;
}
