// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../application/models.js";

export interface BackupResultDTO {
    "cancelled": boolean;
    "fileName"?: string;
    "createdAt"?: string;
    "schemaVersion"?: number;
    "appVersion"?: string;
    "appBuild"?: string;
    "accounts": number;
    "holdings": number;
    "activities": number;
    "verificationResult"?: string;
}

export interface BackupStatusDTO {
    "available": boolean;
    "backupFileName"?: string;
    "createdAt"?: string;
    "schemaVersion"?: number;
    "appVersion"?: string;
    "appBuild"?: string;
    "verificationResult"?: string;
}

export interface CSVConfirmDTO {
    "confirmed": boolean;
}

export interface CSVErrorFileDTO {
    "cancelled": boolean;
}

export interface CSVExportResultDTO {
    "cancelled": boolean;
    "fileName"?: string;
    "profile"?: string;
    "rows": number;
}

export interface CSVFileDTO {
    "cancelled": boolean;
    "token"?: string;
    "profile"?: string;
    "fileName"?: string;
    "delimiter"?: string;
    "hasBom": boolean;
    "headers"?: string[] | null;
    "rowCount": number;
    "columnCount": number;
}

export interface CSVOptionsRequest {
    "token": string;
    "profile": string;
    "delimiter": string;
    "dateFormat": string;
    "decimalSep": string;
    "groupingSep": string;
    "mapping": { [_ in string]?: string } | null;
    "accountsMapping": { [_ in string]?: string } | null;
    "holdingsMapping": { [_ in string]?: string } | null;
    "unresolved": application$0.CSVUnresolvedAction[] | null;
}

export interface CSVPreviewDTO {
    "profile": string;
    "headers": string[] | null;
    "previewRows": (string[] | null)[] | null;
    "stats": application$0.CSVPreviewStats;
    "errors": application$0.CSVRowError[] | null;
    "warnings": application$0.CSVWarning[] | null;
    "unresolved": application$0.CSVUnresolvedName[] | null;
    "canCommit": boolean;
}
