// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateBackup(): $CancellablePromise<$models.BackupResultDTO> {
    return $Call.ByID(1821922794);
}

export function ExportJSON(): $CancellablePromise<$models.ExportResultDTO> {
    return $Call.ByID(3983426512);
}

export function LastBackupStatus(): $CancellablePromise<$models.BackupStatusDTO> {
    return $Call.ByID(3491009104);
}
