// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccountCombinationDTO {
    "accountType": string;
    "balanceSheetRole": string;
    "trackingMode": string;
    "roleLocked": boolean;
    "includeInNetWorth": boolean;
    "includeInPortfolio": boolean;
    "includeInLiquidAssets": boolean;
    "wholeAccountWarning": boolean;
}

export interface CatalogDTO {
    "currencies": string[] | null;
    "instrumentTypes": string[] | null;
    "institutionTypes": string[] | null;
    "quoteSources": string[] | null;
    "instrumentProviders": string[] | null;
    "instrumentCountryCodes": string[] | null;
    "instrumentMarketCodes": string[] | null;
    "accountTypes": string[] | null;
    "balanceSheetRoles": string[] | null;
    "trackingModes": string[] | null;
    "accountCombinations": AccountCombinationDTO[] | null;
    "trackingModesByAccountType": { [_ in string]?: string[] | null } | null;
    "trendRanges": string[] | null;
    "appearances": string[] | null;
    "languages": string[] | null;
    "accents": string[] | null;
    "moneyInReasons": string[] | null;
    "moneyOutReasons": string[] | null;
    "valueUpdateReasons": string[] | null;
    "tradeSides": string[] | null;
}
