// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

/**
 * ActivityQueryRequest mirrors domain.ActivityQuery.
 */
export interface ActivityQueryRequest {
    "accountId"?: string | null;
    "kinds"?: string[] | null;
    "fromLocalDate"?: string;
    "toLocalDate"?: string;
    "afterEffectiveAt"?: string;
    "afterCreatedAt"?: string;
    "afterId"?: string;
    "limit"?: number;
}

/**
 * ChangeCommandKind discriminates ChangeCommandRequest, mirroring the eleven
 * concrete domain.PreviewChange input types. Wails v3's binding
 * generator produces TypeScript models from Go struct declarations, not
 * from a runtime union, so this is one Go struct with every variant's
 * fields optional plus a discriminator, not a Go-level sum type.
 */
export enum ChangeCommandKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ChangeMoneyAdded = "money_added",
    ChangeMoneyRemoved = "money_removed",
    ChangeCashDividend = "cash_dividend",
    ChangeCashTransfer = "cash_transfer",
    ChangeFXConversion = "fx_conversion",
    ChangePositionTransfer = "position_transfer",
    ChangePositionAdjustment = "position_adjustment",
    ChangeTrade = "trade",
    ChangeValueUpdate = "value_update",
    ChangeDebtDraw = "debt_draw",
    ChangeDebtPayment = "debt_payment",
};

/**
 * ChangeCommandRequest is the tagged union the frontend submits for every
 * change kind (Record change, Preview, Fix's replacement command). Money
 * fields are always split into a canonical decimal string amount plus its
 * own currency field; a field irrelevant to the current Kind is simply left
 * empty.
 */
export interface ChangeCommandRequest {
    "kind": ChangeCommandKind;
    "accountId"?: string;
    "fromAccountId"?: string;
    "toAccountId"?: string;
    "settlementAccountId"?: string;
    "debtAccountId"?: string;
    "cashAccountId"?: string;
    "holdingId"?: string;
    "fromHoldingId"?: string;
    "toHoldingId"?: string;
    "instrumentId"?: string;
    "side"?: string;
    "quantity"?: string;
    "added"?: boolean;
    "unitCost"?: string;

    /**
     * Amount is used by MoneyAdded/MoneyRemoved together with Currency.
     */
    "amount"?: string;
    "currency"?: string;
    "sent"?: string;
    "sentCurrency"?: string;
    "received"?: string;
    "receivedCurrency"?: string;
    "sold"?: string;
    "soldCurrency"?: string;
    "bought"?: string;
    "boughtCurrency"?: string;
    "gross"?: string;
    "grossCurrency"?: string;
    "fee"?: string;
    "feeCurrency"?: string;
    "newValue"?: string;
    "newValueCurrency"?: string;
    "principal"?: string;
    "principalCurrency"?: string;
    "interestOrFee"?: string;
    "interestOrFeeCurrency"?: string;
    "reason"?: string;
    "effectiveAt"?: string;

    /**
     * EffectiveLocalDate and EffectiveLocalTime are the wall-clock fields used
     * by the record form. The server resolves them in the immutable History
     * Origin timezone; EffectiveAt remains available for older callers and
     * machine-generated RFC3339 commands.
     */
    "effectiveLocalDate"?: string;
    "effectiveLocalTime"?: string;
    "note"?: string | null;

    /**
     * MutationID is a client-generated UUID that makes Record/Commit/Fix
     * retries idempotent. Empty keeps the unkeyed path for tests and older
     * callers. It is omitted from the payload hash so the same command can
     * reuse one ID.
     */
    "mutationId"?: string;
}

/**
 * DailySnapshotStateDTO mirrors domain.DailySnapshotState.
 */
export interface DailySnapshotStateDTO {
    "householdId": string;
    "dirtyFrom"?: string | null;
    "lastCompletedClosedOn"?: string | null;
}

/**
 * DailyValuationSnapshotDTO mirrors domain.DailyValuationSnapshot totals
 * plus the per-item results that carry Simple classification provenance.
 */
export interface DailyValuationSnapshotDTO {
    "id": string;
    "householdId": string;
    "localDate": string;
    "cutoffAt": string;
    "revision": number;
    "assetsAmount"?: wire$0.MoneyView | null;
    "liabilitiesAmount"?: wire$0.MoneyView | null;
    "netWorthAmount"?: wire$0.SignedMoneyView | null;
    "currency": string;
    "complete": boolean;
    "componentCount": number;
    "missingCount": number;
    "generationReason": string;
    "createdAt": string;
    "items": DailyValuationSnapshotItemDTO[] | null;
}

/**
 * DailyValuationSnapshotItemDTO is one reconstructed component. Simple
 * Account items carry classificationBasis=current-metadata-derived because
 * the bucket name comes from current account_type, not a historical type
 * observation. Composite cash/instrument items omit that field.
 */
export interface DailyValuationSnapshotItemDTO {
    "id": string;
    "accountId": string;
    "holdingId"?: string | null;
    "instrumentId"?: string | null;
    "nativeAmount"?: string;
    "nativeCurrency"?: string;
    "baseAmount"?: wire$0.MoneyView | null;
    "complete": boolean;
    "missingReason"?: string | null;
    "classificationBasis"?: string;
}

/**
 * HistoryOriginDTO mirrors domain.HistoryOrigin.
 */
export interface HistoryOriginDTO {
    "id": string;
    "householdId": string;
    "timezone": string;
    "startedAt": string;
    "createdAt": string;
}
