// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wire$0 from "../wire/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Activity(activityID: string): $CancellablePromise<wire$0.ActivityDTO> {
    return $Call.ByID(537140027, activityID);
}

export function BuildDailyValuationSnapshot(localDate: string): $CancellablePromise<[$models.DailyValuationSnapshotDTO, boolean]> {
    return $Call.ByID(1332356346, localDate);
}

/**
 * CommitChange is kept as a wire alias of RecordChange for old clients.
 * Deprecated: use RecordChange. Application code has a single write path.
 */
export function CommitChange(request: $models.ChangeCommandRequest): $CancellablePromise<wire$0.ChangePreviewDTO> {
    return $Call.ByID(37311191, request);
}

export function CompleteDailySnapshotRange($0: string, targetDate: string): $CancellablePromise<void> {
    return $Call.ByID(2319076695, $0, targetDate);
}

export function DailySnapshotState($0: string): $CancellablePromise<$models.DailySnapshotStateDTO> {
    return $Call.ByID(3301983652, $0);
}

export function FixChange(activityID: string, replacement: $models.ChangeCommandRequest): $CancellablePromise<wire$0.ChangePreviewDTO> {
    return $Call.ByID(1008027433, activityID, replacement);
}

export function HistoryMutationAllowed(): $CancellablePromise<void> {
    return $Call.ByID(295485947);
}

export function HistoryOrigin(): $CancellablePromise<$models.HistoryOriginDTO | null> {
    return $Call.ByID(4016513528);
}

export function HistoryStarted(): $CancellablePromise<boolean> {
    return $Call.ByID(3006043135);
}

export function ListActivities(limit: number): $CancellablePromise<wire$0.ActivityDTO[] | null> {
    return $Call.ByID(3769045223, limit);
}

export function ListActivityPage(request: $models.ActivityQueryRequest): $CancellablePromise<wire$0.ActivityPageDTO> {
    return $Call.ByID(1791038100, request);
}

export function PreviewChange(request: $models.ChangeCommandRequest): $CancellablePromise<wire$0.ChangePreviewDTO> {
    return $Call.ByID(3436872238, request);
}

/**
 * PreviewFixChange is FixChange's read-only counterpart, giving the Fix
 * form the same "preview, then confirm" UX every other change kind gets:
 * it returns the replacement ChangePreview
 * FixChange would commit, computed by inverting the original Activity's
 * effects first, so the previewed number is not double-counted against
 * the original Activity that Confirm will actually remove.
 */
export function PreviewFixChange(activityID: string, replacement: $models.ChangeCommandRequest): $CancellablePromise<wire$0.ChangePreviewDTO> {
    return $Call.ByID(4027359909, activityID, replacement);
}

export function RebuildHistoricalSnapshots(startDate: string, endDate: string): $CancellablePromise<number> {
    return $Call.ByID(2791696898, startDate, endDate);
}

export function RecordChange(request: $models.ChangeCommandRequest): $CancellablePromise<wire$0.ChangePreviewDTO> {
    return $Call.ByID(3328630087, request);
}

export function StartHistory(timezone: string): $CancellablePromise<$models.HistoryOriginDTO> {
    return $Call.ByID(831400526, timezone);
}

/**
 * StartHistoryWithCosts's costOverrides map is keyed by domain.HoldingID in
 * Go; JSON object keys must be strings, so the wire shape is a plain
 * map[string]string keyed by the Holding ID string, parsed here.
 */
export function StartHistoryWithCosts(timezone: string, costOverrides: { [_ in string]?: string } | null): $CancellablePromise<$models.HistoryOriginDTO> {
    return $Call.ByID(1081821496, timezone, costOverrides);
}

export function StartingPointDraft(): $CancellablePromise<wire$0.StartingPointHoldingDTO[] | null> {
    return $Call.ByID(3279200335);
}

export function UndoChange(activityID: string): $CancellablePromise<wire$0.ChangePreviewDTO> {
    return $Call.ByID(1875919204, activityID);
}
