"""Offline, fail-closed importer. Usage: import_logos.py /path/to/bank-logos.
Only the reviewed static path-only SVG subset is accepted.
"""
import hashlib
import json
import math
from pathlib import Path
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from html.parser import HTMLParser

REVISION = 'ffca539a043900fbf2a4fd6a5d32f1706ae5dfd1'
ROOT = Path(__file__).resolve().parents[2]
SVG = 'http://www.w3.org/2000/svg'
ET.register_namespace('', SVG)


def sanitize_svg(raw):
    if re.search(r'<!|<\?(?!xml\s)', raw, re.I):
        raise ValueError('DTD, entities, comments and processing instructions forbidden')
    tree = ET.fromstring(raw)
    if tree.tag != f'{{{SVG}}}svg':
        raise ValueError('expected SVG root')
    for node in tree.iter():
        if node.tag not in {f'{{{SVG}}}svg', f'{{{SVG}}}path'} or (node is not tree and node.tag.endswith('svg')):
            raise ValueError('only a root SVG and static paths are allowed')
        allowed = {'viewBox', 'version', 'width', 'height', 't', 'class', 'style', 'p-id'} if node is tree else {'d', 'fill', 'p-id'}
        if set(node.attrib) - allowed:
            raise ValueError('unsupported attribute')
        if (node.text or '').strip() or (node.tail or '').strip():
            raise ValueError('unexpected text')
        if node is tree:
            vb = node.attrib.get('viewBox', '')
            nums = [float(v) for v in vb.split()]
            if len(nums) != 4 or not all(math.isfinite(v) for v in nums) or min(nums[2:]) <= 0:
                raise ValueError('invalid viewBox')
            style = node.attrib.get('style', '')
            if style and not re.fullmatch(r'width: [\d.]+em;height: 1em;vertical-align: middle;fill: currentColor;overflow: hidden;', style):
                raise ValueError('unsupported style')
            node.attrib.clear()
            node.set('viewBox', vb)
        else:
            if not re.fullmatch(r'[MmZzLlHhVvCcSsQqTtAa\d\s.,+eE-]+', node.attrib.get('d', '')):
                raise ValueError('invalid path data')
            if 'fill' in node.attrib and not re.fullmatch(r'#[0-9a-fA-F]{3}(?:[0-9a-fA-F]{3})?|none', node.attrib['fill']):
                raise ValueError('unsupported paint')
            node.attrib.pop('p-id', None)
    if not list(tree):
        raise ValueError('empty SVG')
    return ET.tostring(tree, encoding='unicode') + '\n'


class Names(HTMLParser):
    def __init__(self):
        super().__init__()
        self.names = {}

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == 'img' and attrs.get('src', '').startswith('./logos/') and attrs.get('alt'):
            self.names[Path(attrs['src']).stem.removesuffix('-rect')] = attrs['alt']


def generate(source):
    if subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip() != REVISION:
        raise ValueError('wrong upstream revision')
    if subprocess.check_output(['git', '-C', str(source), 'status', '--porcelain'], text=True).strip():
        raise ValueError('upstream checkout must be clean')
    names = Names()
    names.feed((source / 'README.md').read_text())
    assets, metadata, provenance = {}, [], []
    for folder in ('logos', 'other'):
        for path in sorted((source / folder).glob('*.svg')):
            relative = path.relative_to(source).as_posix()
            slug = path.stem if folder == 'logos' else 'other-' + hashlib.sha256(relative.encode()).hexdigest()[:16]
            key = 'bank-logo:' + slug
            clean = sanitize_svg(path.read_text())
            source_name = names.names.get(path.stem.removesuffix('-rect'), path.stem)
            name = f'{source_name} ({path.stem})' if source_name != path.stem else source_name
            assets[slug + '.svg'] = clean
            metadata.append({'key': key, 'name': name, 'aliases': [path.stem, source_name], 'file': slug + '.svg'})
            provenance.append({'key': key, 'source': relative, 'originalSha256': hashlib.sha256(path.read_bytes()).hexdigest(), 'sha256': hashlib.sha256(clean.encode()).hexdigest()})
    if len(assets) != 608 or len({x['key'] for x in metadata}) != 608:
        raise ValueError('unexpected asset count or collision')
    output = ROOT / 'frontend/public/bank-logos'
    for name, contents in assets.items():
        (output / name).write_text(contents)
    (ROOT / 'frontend/src/lib/bankLogos.json').write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + '\n')
    (ROOT / 'tools/bank-logos/manifest.json').write_text(json.dumps({'repository': 'https://github.com/icongo/bank-logos', 'revision': REVISION, 'assets': provenance}, ensure_ascii=False, indent=2) + '\n')
    keys = '\n'.join('\t"' + x['key'] + '": {},' for x in metadata)
    (ROOT / 'internal/domain/bank_logos_generated.go').write_text('// Code generated by tools/bank-logos/import_logos.py; DO NOT EDIT.\npackage domain\n\nvar bankLogoKeys = map[string]struct{}{\n' + keys + '\n}\n')
    print(f'Imported {len(assets)} screened SVGs from {REVISION}')


if __name__ == '__main__':
    generate(Path(sys.argv[1]))
