// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountCashValueDTO mirrors domain.AccountCashValue.
 */
export interface AccountCashValueDTO {
    "id": string;
    "accountId": string;
    "amount": MoneyView;
    "effectiveAt": string;
    "createdAt": string;
}

/**
 * AccountDTO mirrors domain.Account. It is shared by the account service
 * (owns Account CRUD) and the portfolio/analytics services (which embed it
 * inside read models such as AccountValuationDTO/AccountGainDTO), so it
 * lives here rather than being duplicated per service.
 */
export interface AccountDTO {
    "id": string;
    "householdId": string;
    "institutionId"?: string | null;
    "groupId"?: string | null;
    "name": string;
    "accountType": string;
    "balanceSheetRole": string;
    "trackingMode": string;
    "defaultCurrency": string;
    "note"?: string | null;
    "iconKey": string;
    "includeInNetWorth": boolean;
    "includeInPortfolio": boolean;
    "includeInLiquidAssets": boolean;
    "openedOn"?: string | null;
    "closedOn"?: string | null;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
    "archivedAt"?: string | null;
}

/**
 * AccountGainDTO mirrors domain.AccountGainView.
 */
export interface AccountGainDTO {
    "accountId": string;
    "holdings": HoldingGainDTO[] | null;
    "totalCost"?: MoneyView | null;
    "currentValue"?: MoneyView | null;
    "realizedGain"?: SignedMoneyView | null;
    "unrealizedGain"?: SignedMoneyView | null;
    "available": boolean;
    "missingReason"?: string;
}

/**
 * AccountRecordDTO mirrors domain.AccountRecord.
 */
export interface AccountRecordDTO {
    "account": AccountDTO;
    "ownership": OwnershipShareDTO[] | null;
    "latestValue"?: AccountValueDTO | null;
    "institutionName"?: string;
    "groupName"?: string;
}

/**
 * AccountValuationDTO mirrors domain.AccountValuation.
 */
export interface AccountValuationDTO {
    "account": AccountDTO;
    "ownership": OwnershipShareDTO[] | null;
    "institutionName"?: string;
    "groupName"?: string;
    "baseValue"?: MoneyView | null;
    "complete": boolean;
    "components": ValuationComponentDTO[] | null;
    "missingInputs": MissingInputDTO[] | null;
}

/**
 * AccountValueDTO mirrors domain.AccountValue.
 */
export interface AccountValueDTO {
    "id": string;
    "accountId": string;
    "valueKind": string;
    "amount": MoneyView;
    "effectiveAt": string;
    "createdAt": string;
}

/**
 * ActivityPageDTO mirrors domain.ActivityPage.
 */
export interface ActivityCursorDTO {
    "effectiveAt": string;
    "createdAt": string;
    "id": string;
}

/**
 * ActivityDTO mirrors domain.Activity.
 */
export interface ActivityDTO {
    "id": string;
    "householdId": string;
    "kind": string;
    "reason": string;
    "effectiveAt": string;
    "effectiveLocalDate": string;
    "createdAt": string;
    "note"?: string | null;
    "reversesActivityId"?: string | null;
    "correctionGroupId"?: string | null;
    "transactionFxRate"?: string | null;
    "tradeDetail"?: TradeDetailDTO | null;
    "dividendDetail"?: DividendDetailDTO | null;
    "resulting"?: EndpointViewDTO[] | null;
    "effects": ActivityEffectDTO[] | null;
}

/**
 * ActivityEffectDTO mirrors domain.ActivityEffect.
 */
export interface ActivityEffectDTO {
    "id": string;
    "activityId": string;
    "sequence": number;
    "role": string;
    "direction": string;
    "target": string;
    "classification": string;
    "accountId"?: string | null;
    "holdingId"?: string | null;
    "instrumentId"?: string | null;
    "money"?: MoneyView | null;
    "quantity"?: string | null;
    "costUnitPrice"?: string | null;
}

export interface ActivityPageDTO {
    "activities": ActivityDTO[] | null;
    "next"?: ActivityCursorDTO | null;
    "hasMore": boolean;
}

/**
 * AllocationDTO mirrors domain.AllocationView.
 */
export interface AllocationDTO {
    "key": string;
    "label": string;
    "amount": MoneyView;
    "shareBps": number;
}

export interface AnalysisDimensionAmountDTO {
    "key": string;
    "label": string;
    "accountId"?: string;
    "instrumentId"?: string;
    "amount"?: SignedMoneyView | null;
}

export interface AssetChangeDTO {
    "summary": AssetChangeSummaryDTO;
    "waterfall": AssetChangeRowDTO[] | null;
    "groups": AssetChangeGroupDTO[] | null;
    "available": boolean;
    "status": string;
    "missingReason"?: string;
    "valuationForced": string | null;
}

export interface AssetChangeGroupDTO {
    "key": string;
    "label": string;
    "amount"?: SignedMoneyView | null;
    "rows": AssetChangeRowDTO[] | null;
}

export interface AssetChangeRowDTO {
    "key": string;
    "label": string;
    "bucket": string;
    "amount"?: SignedMoneyView | null;
}

export interface AssetChangeSummaryDTO {
    "beginningValue"?: SignedMoneyView | null;
    "endingValue"?: SignedMoneyView | null;
    "change"?: SignedMoneyView | null;
}

export interface AssetDriverDetailDTO {
    "driverKey": string;
    "byInstrument": AnalysisDimensionAmountDTO[] | null;
    "byAccount": AnalysisDimensionAmountDTO[] | null;
    "available": boolean;
    "status": string;
    "missingReason"?: string;
    "valuationForced": string | null;
}

export interface AssetTrendDTO {
    "points": AssetTrendPointDTO[] | null;
    "summary"?: SignedMoneyView | null;
    "available": boolean;
    "status": string;
    "missingReason"?: string;
    "valuationForced": string | null;
}

export interface AssetTrendPointDTO {
    "period": string;
    "value"?: SignedMoneyView | null;
    "available": boolean;
    "status": string;
    "missingReason"?: string;
    "valuationForced": string | null;
}

/**
 * BreakdownDTO mirrors domain.BreakdownItem (an exact decimal.Decimal
 * amount, canonicalized here to a string).
 */
export interface BreakdownDTO {
    "key": string;
    "label": string;
    "amount": string;
    "shareBps": number;
    "classificationBasis"?: string;
}

export interface CategoriesDTO {
    "total"?: SignedMoneyView | null;
    "rows": CategoryRowDTO[] | null;
    "available": boolean;
    "status": string;
    "missingReason"?: string;
    "valuationForced": string | null;
}

export interface CategoryActivityRefDTO {
    "date": string;
    "activityId"?: string;
    "accountId"?: string;
    "holdingId"?: string;
    "instrumentId"?: string;
    "amount"?: SignedMoneyView | null;
}

export interface CategoryChildDTO {
    "key": string;
    "label": string;
    "amount"?: SignedMoneyView | null;
}

export interface CategoryDetailDTO {
    "children": CategoryChildDTO[] | null;
    "activityRefs": CategoryActivityRefDTO[] | null;
    "available": boolean;
    "status": string;
    "missingReason"?: string;
    "valuationForced": string | null;
}

export interface CategoryRowDTO {
    "key": string;
    "label": string;
    "accountId"?: string;
    "instrumentId"?: string;
    "assetClass"?: string;
    "amount"?: SignedMoneyView | null;
}

/**
 * ChangePreviewDTO mirrors domain.ChangePreview: the result of previewing,
 * recording, undoing, or fixing a change.
 */
export interface ChangePreviewDTO {
    "activity": ActivityDTO;
    "effects": ActivityEffectDTO[] | null;
    "resulting": EndpointViewDTO[] | null;
    "derivedRate"?: string | null;
    "derivedUnitPrice"?: string | null;
}

/**
 * DividendDetailDTO mirrors domain.DividendDetail.
 */
export interface DividendDetailDTO {
    "holdingId": string;
    "instrumentId": string;
    "amount": MoneyView;
}

/**
 * EndpointViewDTO mirrors domain.EndpointView.
 */
export interface EndpointViewDTO {
    "target": string;
    "accountId"?: string | null;
    "holdingId"?: string | null;
    "name": string;
    "amount"?: string;
    "quantity"?: string;
    "currency"?: string;
}

/**
 * FXPreferenceDTO mirrors domain.FXPreference.
 */
export interface FXPreferenceDTO {
    "householdId": string;
    "currencyA": string;
    "currencyB": string;
    "sourceKind": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * FXQuoteDTO mirrors domain.FXQuote.
 */
export interface FXQuoteDTO {
    "id": string;
    "householdId": string;
    "baseCurrency": string;
    "quoteCurrency": string;
    "rate": string;
    "sourceKind": string;
    "sourceKey": string;
    "quotedAt": string;
    "createdAt": string;
    "delayed": boolean;
}

/**
 * GainGroupDTO mirrors domain.GainGroupView.
 */
export interface GainGroupDTO {
    "key": string;
    "label": string;
    "gain": SignedMoneyView;
    "available": boolean;
    "missingReason"?: string;
}

export interface GroupDTO {
    "id": string;
    "name": string;
    "iconKey": string;
    "color"?: string | null;
    "description"?: string | null;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
    "archivedAt"?: string | null;
}

/**
 * HoldingDTO mirrors domain.Holding.
 */
export interface HoldingDTO {
    "id": string;
    "accountId": string;
    "instrumentId": string;
    "quantity": string;
    "note"?: string | null;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
    "archivedAt"?: string | null;
}

/**
 * HoldingGainDTO mirrors domain.HoldingGainView.
 */
export interface HoldingGainDTO {
    "holdingId": string;
    "accountId": string;
    "instrumentId": string;
    "instrumentName": string;
    "instrumentSymbol"?: string;
    "quantity": string;
    "averageCost": MoneyView;
    "totalCost": MoneyView;
    "totalCostBase"?: MoneyView | null;
    "currentValue"?: MoneyView | null;
    "currentValueBase"?: MoneyView | null;
    "realizedGain": SignedMoneyView;
    "unrealizedGain"?: SignedMoneyView | null;
    "unrealizedGainBase"?: SignedMoneyView | null;
    "instrumentMovement"?: SignedMoneyView | null;
    "currencyMovement"?: SignedMoneyView | null;
    "available": boolean;
    "missingReason"?: string;
}

/**
 * HouseholdDTO, MemberDTO, InstitutionDTO, and GroupDTO are shared read
 * models: both the household service's Bootstrap and the directory
 * service's list/create/update/archive methods return them, so they are
 * defined once here rather than duplicated per service.
 */
export interface HouseholdDTO {
    "id": string;
    "name": string;
    "baseCurrency": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface InstitutionDTO {
    "id": string;
    "name": string;
    "iconKey": string;
    "institutionType": string;
    "countryCode"?: string | null;
    "website"?: string | null;
    "note"?: string | null;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
    "archivedAt"?: string | null;
}

/**
 * InstrumentDTO mirrors domain.Instrument. Shared by the instrument,
 * holding, quote, analytics, and history services.
 */
export interface InstrumentDTO {
    "id": string;
    "householdId": string;
    "name": string;
    "type": string;
    "quoteCurrency": string;
    "symbol"?: string | null;
    "marketCode"?: string | null;
    "countryCode"?: string | null;
    "isin"?: string | null;
    "note"?: string | null;
    "iconKey": string;
    "sortOrder": number;
    "quoteSource": string;
    "providerKey"?: string | null;
    "providerSymbol"?: string | null;
    "createdAt": string;
    "updatedAt": string;
    "archivedAt"?: string | null;
}

/**
 * InstrumentQuoteDTO mirrors domain.InstrumentQuote.
 */
export interface InstrumentQuoteDTO {
    "id": string;
    "instrumentId": string;
    "unitPrice": string;
    "currency": string;
    "sourceKind": string;
    "sourceKey": string;
    "quotedAt": string;
    "createdAt": string;
    "delayed": boolean;
}

export interface MemberDTO {
    "id": string;
    "name": string;
    "iconKey": string;
    "note"?: string | null;
    "sortOrder": number;
    "createdAt": string;
    "updatedAt": string;
    "archivedAt"?: string | null;
}

/**
 * MissingInputDTO mirrors domain.MissingInputView.
 */
export interface MissingInputDTO {
    "kind": string;
    "accountId": string;
    "accountName"?: string;
    "instrumentId"?: string | null;
    "instrumentName"?: string;
    "instrumentSymbol"?: string;
    "quoteSource"?: string;
    "baseCurrency"?: string;
    "quoteCurrency"?: string;
}

/**
 * MoneyView is the wire shape of domain.MoneyView: a canonical decimal
 * string amount plus its three-letter currency code. Every monetary DTO
 * field in internal/wailsapi is either this shape, a plain string produced
 * by a value type's Canonical()/CanonicalAmount() method, or a pointer to
 * one of these when the value can be legitimately absent.
 */
export interface MoneyView {
    "amount": string;
    "currency": string;
}

/**
 * OwnershipShareDTO mirrors domain.OwnershipShare. It is shared by the
 * account service (Account create/update/read) and the history service
 * (activity ownership context), so it lives here rather than in either.
 */
export interface OwnershipShareDTO {
    "memberId": string;
    "shareBps": number;
}

/**
 * QuoteEvidenceDTO mirrors domain.QuoteEvidenceView.
 */
export interface QuoteEvidenceDTO {
    "observationId": string;
    "source": string;
    "sourceKey": string;
    "quotedAt": string;
    "freshness": string;
    "delayed": boolean;
}

/**
 * RealizedGainDTO mirrors domain.RealizedGainView.
 */
export interface RealizedGainDTO {
    "from": string;
    "to": string;
    "currency"?: string;
    "total"?: SignedMoneyView | null;
    "byInstrument": GainGroupDTO[] | null;
    "byAccount": GainGroupDTO[] | null;
    "available": boolean;
    "missingReason"?: string;
}

/**
 * SignedMoneyView is MoneyView's counterpart for values that may be
 * negative (realized/unrealized gain, currency and instrument movement).
 */
export interface SignedMoneyView {
    "amount": string;
    "currency": string;
}

/**
 * StartingPointHoldingDTO mirrors domain.StartingPointHoldingView.
 */
export interface StartingPointHoldingDTO {
    "holdingId": string;
    "instrumentId": string;
    "instrumentName": string;
    "currency": string;
    "quantity": string;
    "unitCost"?: string;
}

/**
 * TradeDetailDTO mirrors domain.TradeDetail.
 */
export interface TradeDetailDTO {
    "side": string;
    "instrumentId": string;
    "holdingId": string;
    "quantity": string;
    "gross": MoneyView;
    "unitPrice": string;
    "fee"?: MoneyView | null;
}

/**
 * ValuationComponentDTO mirrors domain.ValuationComponent.
 */
export interface ValuationComponentDTO {
    "accountId": string;
    "holdingId"?: string | null;
    "instrumentId"?: string | null;
    "instrumentName"?: string;
    "instrumentSymbol"?: string;
    "nativeAmount": string;
    "nativeCurrency": string;
    "baseAmount"?: MoneyView | null;
    "baseAmountExact"?: string;
    "priceEvidence"?: QuoteEvidenceDTO | null;
    "fxEvidence"?: QuoteEvidenceDTO | null;
    "available": boolean;
}
