/**
 * Frontend-only i18next keys that have no internal/i18n counterpart (the
 * navigation grouping decided in
 * docs/migration/wails-v3-navigation-decisions.md#4 groups Members/
 * Institutions/Groups under one "Directory" nav entry, which did not
 * exist as a single concept in the Fyne shell). Kept separate from
 * i18n/locales/*.json (generated by scripts/port-i18n-catalog) so
 * re-running that script never silently drops these.
 */
export const additionsEn = {
  nav: { directory: "Directory" },
};

export const additionsZhCN = {
  nav: { directory: "名录" },
};

export const additionsZhTW = {
  nav: { directory: "名錄" },
};
